### ISSUE TITLE
Enable the nolint linter for Lifecycle Manager

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1013]
**Description:**

In order to address the TODOs (https://github.com/kyma-project/lifecycle-manager/issues/310) in the lifecycle manager, we need to enable the nolint linter

**ACs**:

- [ ] Add configuration for [this linter](https://github.com/ashanbrown/nolintlint); enable `-explain` flag

**Comment by jeremyharisch** [comment]
Which linter are we talking about here? This [one](https://github.com/ashanbrown/nolintlint)? I cannot find any other linters named `nolint`. Plus If we check current state of disabled linters, there is no linter disabled which check for nolint comments.

Clarification is needed?

Or is this about just getting rid of all nolint comments?
