### ISSUE TITLE
Investigate the exhaustruct linter for Lifecycle Manager

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1014]
**Description:**

In order to address the TODOs (https://github.com/kyma-project/lifecycle-manager/issues/310) in the lifecycle manager, we need to enable the exhaustruct linter

**ACs:**
 - [x] Investigate the mentioned linter and decide whether it should be enabled for the Lifecycle Manager
 - [x] Share the findings and decision with the team

**Comment by LeelaChacha** [comment]
Findings from enabling Exhaustruct linter:
- **541 issues**
  - 87 issues due partially initialized *Options structs
  - 82 ctrl.Result structs
  - ca. 200 necessary empty structs:
    - Kyma{}, Module{}, Unstructured{}, ManifestList{}, etc
    - needed for client.Get(), or Controller Manager setup
  - ca. 40 ObjectMeta structs (filled by K8s - eg CreationTimestamps, etc
  - ca. 30 structs initialized empty to be marshelled: eg CustomResourceDefinition{}
  - rest are trvial structs like http.Server, http.Request, tls.Config (not expected to be initialized completely)

**Comment by LeelaChacha** [comment]
**Decision:** We don't enable the linter as we do not see any merit in it. We don't want the subjective opinions of the this linter to be enforced on our code. Enabling this linter would harm the readibility of code, either with unnecessarily initialized structs or exlcusion comments.
