### ISSUE TITLE
Runtime reconciliation with long delay even with watcher enabled

### ISSUE THREAD

**Issue by k15r** [kyma-project/lifecycle-manager#1018]
**Description**

During rollout of the `eventing` modules on ~400 clusters we noticed, that it took lifecycle manager on ~50% of those clusters multiple minutes to rollout the eventing-module CRD.

to test this behaviour i created a small shell script:

Requirements:
- cluster with lifecycle manager deployed
- eventing module template available in experimental channel (change script for different module)
- 2nd cluster as deployment target

```
set -e
timings=timings-$(date +%s)
for i in $(seq 10); do
  kubectl patch kyma default -n kyma-system --type="json" -p="[{\"op\": \"add\", \"path\": \"/spec/modules\", \"value\": [{\"name\": \"eventing\", \"customResourcePolicy\": \"Ignore\", \"channel\": \"experimental\" }] }]" >/dev/null 2>&1

  echo Module enabled

  now=$(date +%s)
  while ! kubectl wait --for condition=established --timeout=60s crd/eventings.operator.kyma-project.io >/dev/null 2>&1
  do 
    sleep 1 
  done
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module enabled ->  CRD in the cluster"
  echo $elapsed >> $timings


  kubectl wait --for=jsonpath='{.status.state}'=Ready kyma/default -n kyma-system >/dev/null
  echo Kyma CR ready
  kubectl patch kyma default -n kyma-system --type="merge" -p="{\"spec\": {\"modules\": [] }}" >/dev/null 2>&1

  echo Module disabled

  now=$(date +%s)
  kubectl -n kyma-system wait --for delete --timeout=60s crd/eventings.operator.kyma-project.io
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module disabled -> CRD removed from cluster"

  kubectl wait --for=jsonpath='{.status.state}'=Ready kyma/default -n kyma-system >/dev/null 2>&1
  echo Kyma CR ready
  echo ----------------------
done
```

**Expected result**

consistent fast reconciliation of the changes in kyma-cr resulting in deployment of CRD within seconds.

**Actual result**

the script enabled -> disables the module 10 times
the seconds it takes from module enabling to crd in cluster is written to a file.
```
0
261
301
300
2
300
299
0
0
0
```

as seen here it took either few seconds (<10) or close to 5mins for the eventing-crd to be available in the cluster

**Comment by janmedrek** [comment]
I have enabled Eventing (fast) on the Stage cluster, the results are as follows:
- `2023-12-06T17:59:28Z` - `kyma alpha enable module eventing-fast -k default -c fast` module enabled with the CLI
- `2023-12-06T17:59:28Z` - Kyma CR went into the `Processing` State immediately
- `2023-12-06T17:59:33Z` - `25a135b1-b286-48de-b73c-f3daf37f8f54-eventing-2375680700` manifest was created
- `2023-12-06T17:59:44Z` - `25a135b1-b286-48de-b73c-f3daf37f8f54-eventing-2375680700` manifest went into the "Processing" State
- `2023-12-06T18:00:18Z` - `eventing-manager` deployment was created in the `kyma-system` namespace
- `2023-12-06T18:00:19Z` - `eventing-manager-cert-handler-dwhh6` pod was scheduled
- `2023-12-06T18:00:26Z` - manager container of `eventing-manager-cert-handler-dwhh6` pod got ready
- `2023-12-06T18:00:31Z` - `eventing` was created in the `kyma-system` namespace
- `2023-12-06T18:00:31Z` - `eventing` went into the `Error` state immediately
- `2023-12-06T18:00:31Z` - State was propagated to the Kyma CR
- `2023-12-06T18:00:39Z` - istio-proxy container of `eventing-manager-cert-handler-dwhh6` pod got ready

The major pause (~35s) is between Manifest creation (in KCP) and resources being applied in the cluster.

As for the results of the script I have run:

Eventing (fast):
- ~45s for the CR to pop up in the cluster after the Module was enabled
- ~70s for the Kyma CR to get into the Ready state
- ~20s for the CR to be gone after the Module was disabled
- ~40s for the Kyma CR to get into the Ready state

Serverless (fast):
- ~80s for the CR to pop up in the cluster after the Module was enabled
- ~145s for the Kyma CR to get into the Ready state
- ~25s for the CR to be gone after the Module was disabled
- ~25s for the Kyma CR to get into the Ready state

Keda (fast):
- ~80s for the CR to pop up in the cluster after the Module was enabled
- ~130s for the Kyma CR to get into the Ready state
- ~25s for the CR to be gone after the Module was disabled
- ~25s for the Kyma CR to get into the Ready state

What I have also observed is that sometimes even after Kyma is in a `Ready` state after deletion the Manifest in the KCP still exists and takes some time to be removed. This somehow blocks the deployment of the module with the same name and channel (KLM sees that manifest exists and does not create a new one, only after the first one is gone new one is created) and is the reason why sometimes it takes a few seconds and sometimes a few minutes.

I'd say that the deployment times have stabilized for now and would not treat it as a critical priority, we still need to experiment with different kyma/manifest worker numbers and requeue intervals.

We will need to have a look into the persisting manifest thing though, enabling and disabling module in a loop is not a regular use-case but we should fix it for the possible corner cases and performance.

**Comment by janmedrek** [comment]
Updated script that I've used:
```
set -e
timings=timings-$(date +%s)
for i in $(seq 10); do
  kyma alpha enable module keda -k default -c fast >/dev/null 2>&1

  echo Module enabled

  now=$(date +%s)
  while ! kubectl wait --for condition=established --timeout=300s crd/kedas.operator.kyma-project.io >/dev/null 2>&1
  do 
    sleep 1 
  done
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module enabled ->  CRD in the cluster"
  echo $elapsed >> $timings


  kubectl wait --for=jsonpath='{.status.state}'=Ready --timeout=300s kyma/default -n kyma-system >/dev/null 2>&1
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module enabled ->  Kyma Ready"
  echo $elapsed >> $timings

  kyma alpha disable module keda -k default -c fast >/dev/null 2>&1

  echo Module disabled

  now=$(date +%s)
  kubectl -n kyma-system wait --for delete --timeout=300s crd/kedas.operator.kyma-project.io >/dev/null 2>&1
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module disabled -> CRD removed from cluster"

  kubectl wait --for=jsonpath='{.status.state}'=Ready --timeout=300s kyma/default -n kyma-system >/dev/null 2>&1
  elapsed=$(( $(date +%s) - now ))
  echo $elapsed seconds: "Module disabled ->  Kyma ready"
  echo $elapsed >> $timings
  echo ----------------------
done
```

**Comment by janmedrek** [comment]
As for deployment - the module CR application is the last step that KLM does when the module is enabled (this is done to make sure that all the resources and CRD are already there), this is why there is a difference in the deployment times between the CR and the manager.

I've created the issue for persisting manifest CR that delays subsequent module enable/disable loops, let's continue discussion there: https://github.com/kyma-project/lifecycle-manager/issues/1154
