### ISSUE TITLE
docs: Check Docs for non-working links

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1019]
**Description**

Check KLM documentation if all links are working as expected.

**Reasons**
Our GH-Action pipeline whihc verify all links, is just working if the link gives us an error response like 404. Means, if we have a broken link to a non existing GH page, it actually give the response 200, since those pages still "exist" in GH but have a non-found file. [Example1](https://github.com/kyma-project/lifecycle-manager/blob/main/controllers/watcher_controller.go), [Example2](https://github.com/kyma-project/lifecycle-manager/blob/main/controllers/kyma_controller.go), both examples are in this [documentation file](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/controllers.md).

**Acceptance Criterias**
- [x] Adjust the pipeline to identify 4xx requests and fail when one pops up
- [x] Fix non-working links

**Comment by janmedrek** [comment]
We would need to check the pipeline - `curl` sometimes returns a zero exit code for the 4xx responses, this can be the same case for the tool used in our GH action. We should investigate that.
