### ISSUE TITLE
Watcher Configuration: Create VS in same namespace as KLM

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1046]
### Description

Currently, the KLM is creating the watcher related VirtualServices in the `default` namespace - this should be avoided on our landscapes. Our setup should only reside in `kcp-system` and `istio-system` namespace.

### Reasons

Resources which the KLM owns should not be in `default` namespace, but in the same namespace.

### Acceptance Criteria

- [x] Make VirtualService namespace configurable (reuse the `flagVar.istioGatewayNamespace`)
    - [x] Changes to be made in [here](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/istio/client.go#L79)
- [x] Adjust test accordingly
- [x] Verify e2e functionality (should already be covered by e2e test)
  - [x] Check whether Istio VirtualService is created in the configured namespace 
- [x] Clean up the old resources in our landscapes

**Comment by nesmabadr** [comment]
The cleanup of old resource on landscapes still needs to be done
