### ISSUE TITLE
[Mandatory Modules] - Reconciliation loop

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#1052]
### Description

Implement New Reconciliation Loop for Handling Mandatory Modules.

### Acceptance Criteria

- [x] Create an additional control loop for Kyma objects that will generate mandatory module Manifest CRs, ensuring the owner reference for the Manifest CR is related to the Kyma CR.
- [x] No changes should be required for the Manifest Controller. This should be verified via end-to-end tests.
- [x] Normal and mandatory modules are accurately differentiated, with mandatory modules not appearing in the Kyma Status.
- [x] If the 'skip reconciliation' condition applies, it should also apply to the mandatory modules.
- [x] When a user marks a custom module template as mandatory in the SKR Kyma or the KCP Kyma and enables the mandatory module in the Kyma CR, the LM should refuse to accept it. Instead, it should place the module in the error state within the status.modules list.
- [x] Sync to SKR must be excluded for mandatory modules.
- [x] Create a follow-up issue to implement metrics that will include all the relevant details.
    - [ ] https://github.com/kyma-project/lifecycle-manager/issues/1184
- [x] Create a follow-up issue to implement e2e test cases.
    - [ ] https://github.com/kyma-project/lifecycle-manager/issues/1185
- [x] All functionalities are thoroughly tested (integration test).
- [x] Create a follow-up issue to document the feature.
    - [ ] https://github.com/kyma-project/lifecycle-manager/issues/1151

### Feature Testing

End-to-End tests, Integration tests, Unit tests

**Comment by ruanxin** [comment]
also don't forget to create documentation regarding this new controller https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/controllers.md
