### ISSUE TITLE
Investigate introducing a cache for storing the secrets

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1070]
**Description:**

We should investigate if we need to introduce a cache for the secrets [here](https://github.com/kyma-project/lifecycle-manager/blob/779ad4652c1cdb7e30b14a7650b76e135c965fe0/pkg/signature/verifier.go#L121) for enhancing performance.

**ACs**

- [ ] Decide if we need to implement a cache for the secrets
- [ ] Cache implementation

**Comment by janmedrek** [comment]
This cache would be related to the sign-verify logic for ModuleTemplates which we do not plan to invest in for now.
