### ISSUE TITLE
Design a no-downtime solution for the CA certificate rotation

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1073]
**Description:**

As a followup to the this [issue](https://github.com/kyma-project/lifecycle-manager/issues/1061), we need to come up with a a no-downtime solution to have the leaf certificates rotated with the CA certificate rotation. The current implementation is [here](https://github.com/kyma-project/lifecycle-manager/pull/1067/files#diff-ef4183438f2f5376deec257e1e7111c13ffbec822976765a5aed36062e6a1771)

**ACs**

- [ ] Investigate how a no-downtime-solution could be implemented
    - [ ] Check if Istio Gateway can handle more than one certificate, if yes how?
    - [ ] Check whats needed to adapt our kustomize AND Helm setup 
    - [ ] Check the effort needed to spend in KLM
- [ ] Come up with a no downtime solution for the CA certificate rotation and propose to the team
- [ ] **Timebox:**  2-3 Days

**Hint**
https://github.com/cert-manager/cert-manager/issues/2478

**Comment by jeremyharisch** [comment]
**ADR**: https://github.com/kyma-project/lifecycle-manager/issues/1428
**Implementation** **Issue**: https://github.com/kyma-project/lifecycle-manager/issues/1430
