### ISSUE TITLE
Flapping state of module in kyma-CR

### ISSUE THREAD

**Issue by k15r** [kyma-project/lifecycle-manager#1080]
### Description

If a module goes into `warning` state during deletion the kyma-CR will report it alternating `Is Deleting` and `Warning`

### Steps to reproduce

eg:
install nats module
create resources on nats:
- port forward nats and use the nats cli
```
nats stream create foo
```
delete the nats module

it will go into warning state as the manager will not remove the reconciler (resources exist on the nats cluster)
the result can be seen in the attachment

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
Kyma CLI Version: x.y.z
If used - k3d/k3s/minikube versions

### Attachments

https://github.com/kyma-project/lifecycle-manager/assets/292906/169ce74e-3bc6-41f7-b065-27fd10fdd38a

**Comment by lindnerby** [comment]
We agreed on investigating the root cause of this behaviour estimate it to 1. Follow-up issue for the fix will be linked here as well.

**Comment by jeremyharisch** [comment]
After investigating into this Issue I have the following conclusion:
- The reason for this flickering is
    1.  In the declarative pkg the status of the Manifest CR will be set to `Deleting` if the DeletionTimestamp has been set and the state is unequal to `Deleting`, then it triggers a new reconiliation
    2. Then if the DeletionTimestamp is set and the state is equal to `Deleting` it continues with the normal workflow of synchronising the resources, thus if the Module CR has the state `Warning` (even with set DeletionTimestamp), the state will be propagated to the Manifest CR -> Manifest has now `Warning` state
    3. Then it starts again with point 1.
- The scenario was "covered" in the E2E test, but due to a wrong implementation of the code, the test was green -> Test needs to be adapted + We need a change in the Template-Operator to simulate this scenario

**Acceptance Criterias:** 
//TODO

**Comment by jeremyharisch** [comment]
Template-Operator Changes will be done in https://github.com/kyma-project/template-operator/issues/147
Unitl then this issue is blcoked.
