### ISSUE TITLE
Kyma CR in processing state over 1 hour after cluster creation on canary

### ISSUE THREAD

**Issue by kolodziejczak** [kyma-project/lifecycle-manager#1095]
### Description

After creating cluster on canary Kyma CR has hanged in the processing for over 1 hour, and modules were not deployed.

### Steps to reproduce

Create cluster on canary.

### Environment Type

Managed

### Environment Info

Default for canary.

### Attachments

All defaults, in the state from creation.

**Comment by janmedrek** [comment]
@kolodziejczak can you provide more info? We would need the Kyma CR at minimum.
