### ISSUE TITLE
Requeue reason metric

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#1112]
### Description

We should add a metric to track the reason of requeue in Kyma control loop.
Name: `lifecycle_mgr_requeue_reason`
Add labels for reason accordingly

### Reasons

As of now we can observe an increase of immediate requeues in lifecycle-manager's control loop of Kymas, as a result of returning `ctrl.Result{Requeue: true}` in various places.
We are interested in the reason of these requeues to figure out which ones are the most frequent ones and how to adapt them, because they may be flooding the worker queues for no valid reason.

### Acceptance Criteria

- [x] Introduce a new metric for tracking the requeue reasons (counter)
  - consider introducing a label for the requeue reason
- [x] Panel added (to the overview dashboard)

**Comment by ruanxin** [comment]
success requeue on STAGE between 11.17.2023 to 03.12.2023

![image](https://github.com/kyma-project/lifecycle-manager/assets/2189071/2a331714-5c22-41b0-8fd0-7128f9532bc5)
