### ISSUE TITLE
Deprecate v1beta1

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1120]
- [x] Configure `+kubebuilder:unservedversion` to each v1beta1 resource, so that in CRD, the `served` attribute is set to `false` for `v1beta1`
- [x] Deploy the change to all landscapes **first** before proceeding
- [ ] Clean up all existing code related to v1beta1 (**keep v1beta1 in CRD definition**)
  - conversion logic: conversion.Hub
  - webhook: kyma, manifest, watcher, (**keep moduletemplate**)
  - disable conversion webhook [patch](https://github.com/kyma-project/lifecycle-manager/blob/5b8c2180aa2e89d2ebaccddef1cbaa934536837c/config/crd/kustomization.yaml#L34-L37)

**Comment by janmedrek** [comment]
Waiting for: https://github.com/kyma-project/lifecycle-manager/issues/1119
