### ISSUE TITLE
Introduce a flag for the `dropVersionFromStoredVersions`

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1134]
### Description

There should be an option to configure a value for the `dropVersionFromStoredVersions` instead of hardcoding it.

The flag and value names should be changed to `dropStoredVersion`.
### 

### Reasons

We want to have a configurable approach for the version migration operation.

### Acceptance Criteria

- [x] `dropVersionFromStoredVersions` renamed to `dropStoredVersion`
- [x] Create a flag for the `dropStoredVersion` value
- [x] If the flag is empty the function should not be called
- [x] Provide a flag in the KCP charts

**Comment by jeremyharisch** [comment]
AC `Provide a flag in the KCP charts` missing
