### ISSUE TITLE
Implementing Monitoring and Observability

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#114]
### Description
To ensure operational readiness for new reconciler product, a comprehensive monitoring and observability solution is essential to have. We want to support operational aspects like observability and tracing by design and want to incorporate it early on.

### AC
- [x] Design and establish KCP Operator Grafana dashboard
  - Reporting on the overall health of KCP Operators (Lifecycle-Manager and Module-Manager)
  - Design and implement key business and systems metrics (both from kubebuilder and custom)
  - [x] Contact and collaborate with SRE for establishing meaningful alerting rule if needed
- [x] Make sure Lifecycle-Manager, Module-Manager log can be collected and presented in KCP Kibana
     example: https://kibana-sf-2eaed983-6984-422e-b6a3-2dbf1c1775cc.cls-03.cloud.logs.services.sap.hana.ondemand.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(columns:!(_source),filters:!(),index:'14462540-9c20-11eb-bfd5-3d4e267b3508',interval:auto,query:(language:kuery,query:klm),sort:!())

### Developer Notes
- Metrics Including but not limited to:
  - [x] Successful Processing Duration 95th percentile for each module reconciliation
    - The duration time of one module state change from `error` or `processing` to `ready`.
    - Design this metrics as Histograms
  - [x] Operator memory, cpu usage (in % and in peak %)
  - [x] Operator worker queue related metrics (from kubebuilder)
  - [x] Operator reconcilation error, success count (from kubebuilder)
- [x] Dashboard data file should persistent and configured in a grafana dashboard ConfigMap, current [control-plane repo reference](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/mothership-reconciler/templates/dashboard.yaml)
- Contact with Huskies to clarify who take responsibility and how to do the integration of Jaeger, Kiali.
  - Jaeger is not in productive ready state
  - Jaeger will be replaced with OpenTelemetry
  - Operator Listener/Watcher is not a typical use case for tracing
  - Conclusion: Don't integrate tracing tool

### Related PR
https://github.com/kyma-project/module-manager/pull/113

**Comment by tobiscr** [comment]
For testing, we can use KCP DEV and deploy the reconciler ecosystem manually until the automated pipelines are ready.

**Comment by tobiscr** [comment]
Further details how to confiugre the observability stack can be provided by @a-thaler .

**Comment by tobiscr** [comment]
Depends on https://github.com/kyma-project/kyma-operator/issues/43 to get finally implemented.

**Comment by tobiscr** [comment]
Waiting for SRE alignemtn on requirements. Moving to blocked now ;)
