### ISSUE TITLE
[Documentation] Watcher CR

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1152]
**Description**

Create a documentation page for Watcher CR under [API](https://github.com/kyma-project/lifecycle-manager/tree/main/docs/technical-reference/api) and reference in [custom-resource-definitions](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/README.md#custom-resource-definitions)

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by c-pius** [comment]
Unassigning myself again as I am heading out for vacation for the rest of the week.
