### ISSUE TITLE
Establish a process to allow SRE can preselect a subset of Kyma cluster to testing new Kyma operator 

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#116]
### Description
To experimental how Kyma operator behavior under real landscape environment, SRE required us to establish a process so that they can select a subset of Kyma which can be managed by new kyma operator.
### AC
- [ ] Establish an instruction document, describe the steps for the configuration in detail, delivery to SRE as a guidance.

**Comment by tobiscr** [comment]
Let's clarify what the SRE requirements are.
