### ISSUE TITLE
Performance alerting

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#1166]
### Description

We want to have alerts in place to be notified on performance issues with KLM.
Therefore we should define alert rules on performance metrics, especially interesting are:
* Controller-runtime Metrics:
    * `workqueue_depth`
    * `workqueue_adds_total` (total number of adds handled by work queue)
    * `workqueue_retries_total` (total number of retries handled by work queue)
    * `workqueue_queue_duration_seconds` (how long an item stays in the work queue)
    * `workqueue_work_duration_seconds` (how long processing an item from work queue takes)
    * `controller_runtime_reconcile_errors_total` (total number of reconciliation errors)
    * `controller_runtime_reconcile_time_seconds` (time taken by a controller to reconcile)

* Go Runtime Metrics:
    * `go_goroutines` (number of goroutines that currently exist)
    * `go_memstats_alloc_bytes` (number of bytes of allocated heap objects)
    * `go_memstats_gc_cpu_fraction` (the fraction of this program's available CPU time used by the GC since the program started)

Alert rules surrounding these metrics should be routed via alertmanager config to corresponding slack channels for each landscape:
* jellyfish-alerts-dev
* jellyfish-alerts-stage
* jellyfish-alerts-prod
### Reasons

We aim to establish automatic alerts for performance issues with KLM. This way, we'll receive immediate notifications about the problems rather than constantly needing to manually check for them.

### Acceptance Criteria

- [x] Come up with reasonable alertrules; thresholds
- [x] KLM performance related Alert Rules are configured per landscape
- [x] Alerts are routed to Slack channel per landscape

**Comment by Tomasz-Smelcerz-SAP** [comment]
The `go_memstats_gc_cpu_fraction` is not present in the metrics for the lifecycle manager.
