### ISSUE TITLE
Increase Manifest CR workers for KCP PROD

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1170]
The performance of Manifest controller is not good atm, latency increased to more than 1 mins, and around 6k Manifest CR constantly waiting in queue.
![image](https://github.com/kyma-project/lifecycle-manager/assets/2189071/ac660e4a-e371-4317-98d9-d3a9b3d8de4b)

AC
- [ ] increase the `max-concurrent-manifest-reconciles` to 50 on `management-plane-charts` repo for KCP PROD profile
- [ ] after release:
  - verify CPU usage is still acceptable
  - verify worker queue metrics performance better
  - if CPU usage is worse, try to reduce to another value (~40)
  - create follow-up if worker queue metrics are still "bad"

**Comment by jeremyharisch** [comment]
After having it set to 50 for two hours, we get the following results:
- CPU usage slightly increase, but it looks still acceptable
- Memory usage nearly the same
- Work Queue Latency decreased by 50% (thats what we wanted)
- Work Queue Depth not always at maximum as before (also good improvement)

![Image](https://github.com/kyma-project/lifecycle-manager/assets/48282931/51fb302a-05d4-4c54-b410-9a48e0294962)

![Image](https://github.com/kyma-project/lifecycle-manager/assets/48282931/5283a31b-c059-431e-b3b9-8592e349eec8)
