### ISSUE TITLE
Watcher: Authorized CA Certificate

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1175]
### Description

The current PKI setup for the runtime-watcher, uses an untrusted self-signed CA Certificate. We have a security claim by SGS to use a trusted CA Cert instead. 

What does that mean? The PKI setup can stay as it is described [here](https://github.com/kyma-project/runtime-watcher/blob/main/docs/architecture.md) and how it is currently implemented. But the CA Cert should not be unstrusted self-signed. Thus, we should remove the [self-signed ClusterIssuer](https://github.com/kyma-project/lifecycle-manager/blob/05f85e70640adcb993978d5be971f131f935f9ee/config/watcher/certificate_setup.yaml#L6), and instead of referencing the removed ClusterIssuer in our CACert, we need to reference a trusted Issuer. We should already have one in the KCP setup, more infos should be gathered with the SREs.

### Reasons

- Stay compliant and more secure as before
- Solve medium SGS incident

### Acceptance Criteria

- [ ] Remove [self-signed ClusterIssuer](https://github.com/kyma-project/lifecycle-manager/blob/05f85e70640adcb993978d5be971f131f935f9ee/config/watcher/certificate_setup.yaml#L6)
- [ ] Replace [Issuer reference](https://github.com/kyma-project/lifecycle-manager/blob/05f85e70640adcb993978d5be971f131f935f9ee/config/watcher/certificate_setup.yaml#L28C4-L31C27) for our CACert with a trusted non-selfsigned Issuer
    - [ ] Talk to SREs which trusted Issuers we have in KCP and which we can leverage
- [ ] Update the [architecture diagram ](https://github.com/kyma-project/runtime-watcher/blob/main/docs/architecture.md)
- [ ] Update documentation in [runtime-watcher](https://github.com/kyma-project/runtime-watcher/tree/main)
- [ ] Update documentation in [lifecycle-manager](https://github.com/kyma-project/lifecycle-manager)
- [ ] Adapt test setups:
    - [ ] Introduce self-signed ClusterIssuer in [test-setup kustomize](https://github.com/kyma-project/lifecycle-manager/tree/main/config/watcher_local_test) 
    - [ ] Write a patch to overwrite the IssuerReference of the CACert with the self-signed Issuer
    - [ ] Make sure all tests pass

**Comment by jeremyharisch** [comment]
After clarification with the SREs and @TorstenD-SAP we agreed on that no changes need to be made to our setup. This is due to the fact, that the root CA is the only CA we trust and this is owned by us and does not need to be signed by a trusted authority.

**Comment by TorstenD-SAP** [comment]
Security Exception created: https://securityjira.wdf.sap.corp/browse/SEP-1684

**Comment by TorstenD-SAP** [comment]
The Security Exception was rejected because the corresponding Security Procedure is not applicable. I will align with SGS how to proceed with the open findings from the external security scans.

**Comment by TorstenD-SAP** [comment]
The solution we have in place was approved by SGS, an exception was created at the scanner (ID: VUL0183233, approved by I538305).
