### ISSUE TITLE
Remove namespace/name pattern for RemoteModuleTemplateRef

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1186]
### Description

The logic to get moduletemplate is not namespaced scoped, and the [existing logic](https://github.com/kyma-project/lifecycle-manager/blob/9be2538f0201fe61eb7ac1f620242137f6178c74/pkg/channel/lookup.go#L305-L313) also support finding moduletemplate name only with name, there is no need to support this `namespace/name` pattern, which brings confusion to end user.

### Acceptance Criteria

- [ ] remove the logic [here](https://github.com/kyma-project/lifecycle-manager/blob/9be2538f0201fe61eb7ac1f620242137f6178c74/pkg/channel/lookup.go#L305-L309)
- [ ] update the attribute description https://github.com/kyma-project/lifecycle-manager/blob/0d4dd484cca9fdb8e8b6a74bbb1debac4a1c21d0/api/v1beta2/kyma_types.go#L81-L83 and related document
- [ ] refactoring existing integration test and and new e2e test for RemoteModuleTemplateRef enabling

### Feature Testing

Integration tests, End-to-End tests

**Comment by janmedrek** [comment]
We need to iterate over the feature at all - it may not be worth keeping and maintaining.

**Comment by janmedrek** [comment]
No longer relevant: https://github.com/kyma-project/lifecycle-manager/issues/1252
