### ISSUE TITLE
Create a new Operator/Control-Loop responsible for establishing lesser privileged Kubeconfigs for SKR Interaction

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/lifecycle-manager#119]
As a Control-Plane Operator, I want to make sure that all Operators that are interacting with my Runtimes that are managed through the Control Plane have only limited Access. I want to do this to 

- Ensure that all Operators only can work with the resources that they declare
- Ensure that no Operator can achieve privilege Escalation
- No malicious attacker can achieve privilege Escalation through gaining control of a privileged Operator

As such I want to achieve a new way of reading and distributing Kubeconfigs.

AC:

- [ ] Every Operator managed by Kyma-Operator should receive new Kubeconfigs
- [ ] Every new Kubeconfig should be rotated out regularly
- [ ] Every Kubeconfig should be limited to a set of Privileges based on preset RBAC Information
- [ ] The RBAC Information required for every module is depending on its business needs, so it needs to be configurable (e.g. one Controller might require Read-Only Access to Pods, while another might even touch CRDs)
- [ ] The Controller should expect a "Master" Kubeconfig, or privileged Access in the Control Plane and should run in a different namespace and name together with different roles than all other Control Loops
- [ ] The Master Kubeconfigs should ideally never be persisted in Cluster, but if they have to be, then they should be stored in the safe namespace
- [ ] The Kubeconfigs that are generated should bind a user with a RoleBinding of the lesser Privileged Roles

**Comment by tobiscr** [comment]
Obsolete, closing it
