### ISSUE TITLE
E2E config improvement

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#1224]
### Description
Both E2E workflows of lifecycle-manager and runtime-watcher have overlapping config and setup requirements. Let's extract and share the setup requirements steps. Have a look at [re-using workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow).
Possible further investigation: 
    * https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-from-your-private-repository
    * https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization

### Reasons

We want to update versions and make changes to prerequisites of e2e tests only one time and not per repository.

### Acceptance Criteria

- [ ] Setup steps in e2e tests are shared between lifecycle-manager and runtime-watcher: install kubectl, checkout repository, setup go, install istio, install kyma cli, install certmanager cli, install k3d, provision clusters
- [ ] Split the setup into three separate workflows: "install prerequisites" and "create clusters" (which includes kubeconfig handling and etc/hosts patching), "template-operator setup" (only required for certain matrix entries, but includes, repository checkout, module creation, apply module). Feel free to come up with a better split of workflows if applicable.
- [ ] Align steps from runtime-watcher towards -> lifecycle-manager because in runtime-watcher they have been reworked already quite a bit!

**Comment by c-pius** [comment]
Sharing overall seems to work (assuming we are allowed to run actions from other repositories of our own org):

- test actions defined in public repo: https://github.com/c-pius/lifecycle-manager/tree/chore/shared-github-actions/.github/actions
- run in local repo: https://github.com/kyma-project/lifecycle-manager/actions/runs/8570333790/job/23488034467?pr=1451
- run in another repo: https://github.com/c-pius/playground/actions/runs/8570662789/job/23489071011?pr=1

**Comment by c-pius** [comment]
## Proposed Structuring

Legend

```
- Level 1: Job
  - Level 2: Action used in job step
    - Level 3: Action used in action step
```

### KLM

- Wait for image build
  - Wait for image build
- E2E Tests
  - Checkout KLM
  - Checkout Template Operator
  - Install Prerequisites
    - Install kubectl
    - Install istioctl
    - Install kymacli
    - Install cmctl
    - Install k3d
  - Setup golang
  - Configure etc/hosts
  - Provision SKR
  - Provision KCP
  - Configure kubectl (merge config, expose env vars, use kcp-config)
  - Deploy Istio
  - Deploy Cert Manager
  - Configure KLM Deployment (specific to KLM tests)
    - override kustomize
    - patch purge finalizers
    - ...
  - Deploy KLM
  - [in various configurations]Create and apply template operator
  - Expose Metrics endpoint
  - Run tests

### Watcher

- Wait for image build
  - Wait for image build
- E2E Tests
  - Checkout Watcher
  - Checkout KLM
  - Checkout Template Operator (TODO: check if really needed)
  - Install Prerequisites
    - Install kubectl
    - Install istioctl
    - Install kymacli
    - Install cmctl
    - Install k3d
  - Setup golang
  - Configure etc/hosts
  - Provision SKR
  - Provision KCP
  - Configure kubectl (merge config, expose env vars, use kcp-config)
  - Deploy Istio
  - Deploy Cert Manager
  - Configure KLM Deployment (specific to watcher)
    - patch image name
  - Deploy KLM
  - Get cluster info
  - Run tests

**Comment by lindnerby** [comment]
Re-opening to implement the re-use of shared workflow within runtime-watcher.
