### ISSUE TITLE
Improve KLM docs with findings/questions from recent onboarding

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1249]
**Description**

- [Architecture](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/architecture.md)
  - maybe rework the diagram
    - align the multiples, e.g.: (for me, the multiples where a bit confusing and I assumed there is one super big KymaCR in KCP that describes all SKR clusters)
      - SKRs being multiples
      - KymaCR in KCP being multiple whereas in SKR being single
      - ManifestCRs in KCP being multiples
    - consider using TAM block diagram notation
      - it is heavily used and understood within SAP, and should also be rather clear to the outside
    - add the "outside" access to KCP
      - e.g., actor access to KymaCR in KCP (for me, it was for instance not clear from the document how a Kyma installation is removed again)
  - phrase *"manages operators free of dependency trees"* may need further explanation
  - phrase *"rendered module"* may need further explanation
- [ModuleTemplate Custom Resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md)
  - starts with *"contains 3 main parts that are used to initialize and resolve modules"*, but then lists all `spec` attributes without further reference of what the 3 main parts are
- [Kyma Custom Resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md)
  - phrase *"contains 3 fields that are together used to declare the desired state of a cluster"* with the following 2 points list (even though 3 fields are mentioned) is a bit confusing
- [Controllers](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/controllers.md)
  - section on [Remote Synchronization](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/controllers.md#remote-synchronization) may be outdated
    - understood from Jay that by now, KCP KymaCR only includes the "initial spec" and up to date status; for module installation, the source of through is `spec` from SKR KymaCR
    - mentioned `ReplaceWithVirtualKyma` doesn't seem to exist in sync handlers any more
- [Control Plane Quick Start](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/user-tutorials/01-10-control-plane-quick-start.md)
  - step 3 in [provisioning](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/user-tutorials/01-10-control-plane-quick-start.md#provision-a-kcp-cluster) uses outdated link
    - new location seems to be `https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml`
  - link to kustomization in [Deploy Lifecycle Manager](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/user-tutorials/01-10-control-plane-quick-start.md#deploy-lifecycle-manager) goes to 404 when called directly, but still seems to work
    - browser accessible link seems to be `https://github.com/kyma-project/lifecycle-manager/tree/main/config/control-plane`, but specifying that one fails
    - it may justify a small note/explanation

**Reasons**

- keep the docs nice and shiny

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by janmedrek** [comment]
Please align with THE @jeremyharisch and THE @c-pius on the diagram. 🙂
