### ISSUE TITLE
Operators under same namespace and avoid resource name collision

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#127]
**AC**
- [x] All deployed operators under namespace `kcp-system`
- [x] Avoid resource name collision by provide unique namePrefix in each operator repo.
  - [x]  lifecycle-manager with namePrefix ` lifecycle-manager-` https://github.com/kyma-project/lifecycle-manager/pull/139 
 - [x] module-manager with namePrefix `module-manager-`
 - ❌   watcher-operator with namePrefix `watcher-operator-` 
- [x]  Write guide about how to do this changes in template operator doc. https://github.com/kyma-project/lifecycle-manager/pull/172

**Comment by jakobmoellersap** [comment]
closing as all prefixes are set and all labels corrected
