### ISSUE TITLE
Test:  Readiness of Manifest CR should depend on `spec.customStateCheck` field

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1286]
### Description

[Here](https://wiki.one.int.sap/wiki/display/kyma/Lifecycle+Manager+Integration+Test) we have documented down needed test which should be implemented. Unfortunately, we forgot to implement one test case

- Given a ModuleTempate
- And it contains a customized spec.customStateCheck
- Then the readiness of Manifest CR should depend on this customized field

### Reasons

The custom state check function processCustomStateCheck should have more unit test

### Acceptance Criteria

- [ ] Implement Integration Test which covers described scenario

**Comment by janmedrek** [comment]
The feature for custom state check logic will be dropped with the: https://github.com/kyma-project/lifecycle-manager/issues/1472
