### ISSUE TITLE
Excessive logging in case of misconfigured Kymas/SKR-secrets

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#1290]
### Description

Observed on DEV: In case of an "orphaned" Kyma, the Lifecycle-Manager floods the log stream with identical error messages.
Currently there are many orphaned Kymas on DEV, and so the log collection mechanism is overloaded because of that behavior.

Details:
The orphaned Kyma is a Kyma for which the SKR doesn't exist anymore. The secret with the kubeconfig still exists though, preventing LM from deleting the Kyma object.
The particular log entry I observed: `E0204 01:59:00.001032 1 memcache.go:265] couldn't get current server API group list: Get "https://api.ab2ec24.dev.kyma.ondemand.com/api": dial tcp: lookup api.ab2ec24.dev.kyma.ondemand.com on 10.4.0.10:53: no such host`.
I counted 706 such log entries for that single Kyma produced within one minute, in a randomly chosen period.

A/C:
[] - reduce the number of log entries produced for a single Kyma in case of "host not found" errors
[] -  (stretch) try to design the mechanism to be easily extensible, so that LM can handle other similar errors (like `connection reset`), which may also occur in described conditions, in the same way.

### Steps to reproduce

TBD

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
Kyma CLI Version: x.y.z
If used - k3d/k3s/minikube versions

**Comment by c-pius** [comment]
❗ Not sure if this is related, so take with care...

One thing I observed while testing another thing: if I shut down the local skr cluster while the kcp cluster is running, logs and metrics are also going bonkers reaching hundreds of entries within no time. Log messages are different though (saying "connection reset by peer").

The metric that is sky rocketing is `lifecycle_mgr_requeue_reason_total{requeue_reason="manifest_sync_resources",requeue_type="unexpected"}`. If we look at that metric in Plutono for the last 30 days, we can see some crazy numbers as well (one pod was writing 15 million entries in less than 24 hours)

**Comment by jeremyharisch** [comment]
Blocked by https://github.com/kyma-project/lifecycle-manager/pull/1297
