### ISSUE TITLE
Prepare and test compatibility with next k8s version 1.28

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1295]
### Description

Lifecycle Manager should be compatible with the new K8S version.

We can consider creating a pipeline for testing such scenarios.

### Reasons

According to the security requirements and the upgrade process for the Control Plane, we need to be aligned with specific K8S versions.,

### Acceptance Criteria

- [x] Adjust GH actions to accept the K8S version as an input parameter
- [x] Add the manual trigger for that action
- [x] Lifecycle Manager deployed and tested with the K8S version 1.28

**Comment by lindnerby** [comment]
Running e2e with k8s 1.28.7 results in failure.
Logs can not be retrieved anymore, so a [follow-up](https://github.com/kyma-project/lifecycle-manager/issues/1323) is needed to enable 1.28+ compatibility.
