### ISSUE TITLE
Implement module Commands in the modulectl

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1306]
**Description**
In the new developer facing CLI, we need to cover some old functionalities from the Kyma-CLI.

**Issues**
    - https://github.com/kyma-project/modulectl/issues/9
    - https://github.com/kyma-project/modulectl/issues/10

**Comment by janmedrek** [comment]
Closing in favor of: https://github.com/kyma-project/lifecycle-manager/issues/1274
