### ISSUE TITLE
Add a test case for the ssa apply when it is supported by the controller runtime

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1333]
### Description

The controller runtime doesn't support ApplyPatchType for the fake client. Once this is supported we want to add a test case for this in the [ssa_test](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/declarative/v2/ssa_test.go).

This could be the test case:
`{
			"simple apply",
			args{
				clnt:  fakeClientBuilder,
				owner: client.FieldOwner("test"),
			},
			[]*resource.Info{&resource.Info{Object: pod}},
			nil,
		},`

Here is the issue to track if it's support https://github.com/kubernetes/client-go/issues/970

### Reasons

Right now the controller runtime does not support the ApplyPatchType for fake client

### Acceptance Criteria

- [ ] Re-add test case for ApplyPatchType in ssa test

**Comment by janmedrek** [comment]
@nesmabadr I see the K8S issue got closed by the stalebot as `Not Planned`. Do we have other options?
