### ISSUE TITLE
 Implement ModuleConfig

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1368]
### Description

Based on ADR https://github.com/kyma-project/lifecycle-manager/issues/1104, introduce a new CR - `ModuleConfig` to persist module configuration data in KCP.

Lifecycle Manager is the producer for ModuleConfig, collecting content from the associated Module CR . When the Module CR is created or updated, the Lifecycle Manager will update the corresponding ModuleConfig in KCP.

### Acceptance Criteria
- [ ] #1371
- [ ] #1369
- [ ] #1370

**Comment by LeelaChacha** [comment]
@ruanxin should we also have an issue to update our e2e test infrastructure to support testing scenarios with ModuleConfigs and SyncResources? We will need to add some dynamicity to the template operator for this
