### ISSUE TITLE
Finalizer removal inconsistent between Kyma and Purge controllers

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1402]
### Description

While investigating https://github.com/kyma-project/lifecycle-manager/issues/1400, we have noticed that we may have inconsistent error handling and finalizer removal between Kyma and Purge controller.

The `access secret not found` error described in the ticket originates from here: https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/remote/cluster_client.go#L34 (notice that we are not wrapping any other error)

This error surfaces in Kyma controller [here](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/controller/kyma_controller.go#L123-L134) and Purge controller [here](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/controller/purge_controller.go#L85-L95). In the Kyma controller, we remove ALL finalizers from the KymaCR if it matches above error. In Purge controller however, we are removing the purge finalizer if the error classifies as `IsNotFound` which is NOT the case for the `ErrAccessSecretNotFound`. Hence, on `ErrAccessSecretNotFound` we requeue without removing finalizers.

We should consider to align this behavior between both controllers.

### Steps to reproduce

n/a

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
Kyma CLI Version: x.y.z
If used - k3d/k3s/minikube versions

**Comment by janmedrek** [comment]
Would need to be re-verified after the code update first.

**Comment by janmedrek** [comment]
Closing in favor of: https://github.com/kyma-project/lifecycle-manager/issues/2055
