### ISSUE TITLE
Remove the drop-stored-version flag from lifecycle manager

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1410]
### Description

Remove the drop-stored-version flag when the new storage version dropper is synced to all landscapes. Right now, it is only on dev and stage.

### Reasons

Since we introduced the new [storage version dropper](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/crd/storage_version_dropper.go) to support different versions depending on the resource kind, we no longer need the `drop-stored-version` flag.

### Acceptance Criteria

- [x] Ensure the `drop-stored-version` flag is no longer in any of the landscapes
- [x] Remove the `drop-stored-version` flag from the lifecycle manager code

**Comment by janmedrek** [comment]
Waiting for the Helm switch to be completed (to not duplicate the work needed)
