### ISSUE TITLE
Design release pipeline in internal repo

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1457]
### Description

To streamline our release workflow with Helm charts, we've introduced a new process where the `appVersion` in the `Charts.yaml` file needs to be updated for each release. To ensure the accuracy and quality of our releases, we propose implementing a manual release process where certain quality checks are conducted before merging the release PR.

Create the following GitHub-Actions:
1. Check if the given `appVersion` is the latest release version.
    - Required check
2. Run all e2e tests from lifecycle manager repo.    
    - Setup an e2e test environment based on helm charts config.
    - Check which E2E Test fits for helm chart config
    - Reuse existing GH Actions form KLM repo

The pipelines are getting triggered if a PR gets opened which includes changes to the `charts.yaml`.

### Acceptance Criteria

- [x] Implement above mentioned pipeline as a required job before merge in management plane charts.

**Comment by jeremyharisch** [comment]
Test PR: https://github.com/jeremyharisch/charts-testing/pull/1
