### ISSUE TITLE
Add more detailed Dashboard for Warden Rollout

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1468]
### Description

Currently we have a dashboard as an overview for the status for the Warden Module. To get a better insight, we should add dashboard to see how many Warden instances are rolled out and how many should be rolled out.

Similar to the dashboard of the Runtime-Watcher.
![Screenshot 2024-04-12 at 12 43 45](https://github.com/kyma-project/lifecycle-manager/assets/48282931/b4e9ee60-ae17-4e18-93cf-ee859bd6d0a4)

### Reasons

Gives us more insight and confidence about the rollout

### Acceptance Criteria

- [x] Create new dashboard for Warden mandatory module
   - [x] Percentage of rolled-out instances
   - [x] Maybe add which images are deployed, to be discussed

**Comment by c-pius** [comment]
Verified on DEV now. See two additional PRs linked for the config missing to get this deployed properly.



![Image](https://github.com/kyma-project/lifecycle-manager/assets/22994291/9f6c0c29-91a2-4a5d-9dfc-aa1fea53f709)
