### ISSUE TITLE
Add Channel field to Manifest.Spec instead of the Channel label

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1477]
### Description

In the Manifest, we have the channel defined as a label `operator.kyma-project.io/channel`. We need to stop depending on this label and introduce a `Channel` field in the Manifest.Spec instead.

### Acceptance Criteria

- [ ] Introduce an optional Channel field to the v1beta2.Manifest spec
- [ ] Prioritize using the spec field over the label
- [ ] Remove adding the channel label from the manifest
- [ ] Create an issue to have the Channel field mandatory in the next API version.
- [ ] Make sure backwards compatibility is handled and tested.

**Comment by c-pius** [comment]
In https://github.com/kyma-project/lifecycle-manager/issues/1681 it has been decided that ModuleTemplates will be tied to versions. An assignment of modules to channels will happen via a separate CR, but eventually, we will always install a version of a module. Version is already part of the manifest. We need to evaluate if we even need channel info as part of the Manifest at all, or if we can completely rely on the version.

**Comment by c-pius** [comment]
Closing for the reasons mentioned above. Deprecation of the label should be handled in: https://github.com/kyma-project/lifecycle-manager/issues/1839
