### ISSUE TITLE
[Research] Figure out if possible to get resources under watch without consume API server

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1481]
A research topic, the goal is to make [httpClient](https://github.com/kyma-project/lifecycle-manager/blob/c2b2dd5713328990d1eb190c0108c36f21cb33cf/internal/controller/kyma_controller.go#L69) configured in the kyma controller to get the cached resources without consume API server.

**Notice**
It's not a native behaviour how controller-runtime `Informer` is designed for, check the document [here](https://vivilearns2code.github.io/k8s/2021/03/12/diving-into-controller-runtime.html), but I see this issue is a good research topic for us familiar with how internally controller-runtime list and watch behaviour works.

## AC
- [x] Do research to see if we can achieve the goal
- [x] Present to the team about the findings, especially how the list-and-watch works.

Timebox: 3 days

**Comment by LeelaChacha** [comment]
We found that controllers inherit the httpClient from their manager. This client is already set up with a cache on GVK basis. When the controller is built, a long running connection is started with the API server, and the cache is updated on every event that occurs in the API server. This cache is used when Get() or List() operations are performed in the client.
This mechanism only works for resource which are specified within the Watches() method when building the controller. E.g.:
```
controllerBuilder := ctrl.NewControllerManagedBy(mgr).For(&v1beta2.Kyma{}).
		Named(KymaControllerName).
		WithOptions(options).
		WithEventFilter(predicates).
		Watches(
			&v1beta2.ModuleTemplate{},
			handler.EnqueueRequestsFromMapFunc(watch.NewTemplateChangeHandler(r).Watch()),
			builder.WithPredicates(predicates),
		) // This method enables the caching and watching of the resource
```

**Comment by janmedrek** [comment]
@ruanxin please provide a follow-up tickets

**Comment by jeremyharisch** [comment]
Follow-Up: https://github.com/kyma-project/lifecycle-manager/issues/1456
