### ISSUE TITLE
Drop multiple ways for referencing modules in Kyma CR

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1521]
### Description

Currently, it is possible to reference the Kyma Module in [multiple ways](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md#specmodules). There should be only one way - using the label value of `operator.kyma-project.io/module-name`.

### Reasons

There is no need to support multiple ways of referencing Module Templates, we plan to stop synchronizing ModuleTemplates to SKRs.

### Acceptance Criteria

- [x] FQDN is no longer supported as a method of referencing Kyma Modules
- [x] Passing the namespace/name of a ModuleTemplate CR  is no longer supported as a method of referencing Kyma Modules
- [x] Documentation adjusted
- [x] Tests adjusted

**Comment by amritanshusikdar** [comment]
While working on this issue, several problems with the local test setup guide of the Kyma Lifecycle Manager were discovered. The fix / updated documentation has been proposed [here](https://github.com/kyma-project/lifecycle-manager/pull/1680).

**Comment by jeremyharisch** [comment]
Additional AC:

- [ ] Please create Follow-Up Issue to check whether any SKR cluster uses the "old" way of referencing the modules.

**Comment by c-pius** [comment]
> check whether any SKR cluster uses the "old" way of referencing the modules. 

IMHO, this must be verified before merging the related PR. We need to know if we break any existing clusters and if so, first migrate them on using the approach supported that is left.

**Comment by lindnerby** [comment]
As discussed we want to do a thorough verification on Prod landscape with namespaced name and FQDN references as a last step to close this issue.

**Comment by c-pius** [comment]
> As discussed we want to do a thorough verification on Prod landscape with namespaced name and FQDN references as a last step to close this issue. And please clean-up/archive related issue: #1682

Comment: during refinement of the other ticket, it seemed like the alternative approaches for referencing a module were not working because of an other change introduced earlier... If it can indeed be verified that other approaches are not working right now already, and given that nobody complained until now, we can move forward with this change and close the other issue.
