### ISSUE TITLE
Split KymaReconciler for single/dual cluster mode

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#1525]
### Description

Many ependencies are unnecessary for single cluster mode, but are instantiated for kyma.Reconciler. We can already select during setup which mode we need KLM to to run in, either single cluster mode or dual cluster (default) mode. The idea here is to split kyma.Reconciler into two structs for each mode accordingly. 

Since the dual cluster reconciler is executing exactly the same steps as the single cluster reconciler AND more, see cases of `r.SyncKymaEnabled(kyma)` being true, we can consider make use of the [Template Method](https://refactoring.guru/design-patterns/template-method) and [Decorator](https://refactoring.guru/design-patterns/decorator) design patterns. This could roughly look like the following:

### Acceptance Criteria

- [ ] Separate reconcilers for Kyma in single and dual cluster mode, by reusing as much functionality as possible
- [ ]

**Comment by janmedrek** [comment]
First, we need to decide whether it makes sense to keep the single-cluster mode at all.

I recon no end-users using that feature, perhaps it does not make sense to maintain it.
