### ISSUE TITLE
Stop aggregate module cr state into manifest cr

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1554]
### Description

Related epic: https://github.com/kyma-project/lifecycle-manager/issues/1471

At the moment, KLM aggregates module cr state from skr cluster into manifest cr, which makes manifest cr state mixed with module cr, in order to achieve the goal of the epic, we should stop this aggregate process.

### Reasons

not mix the module status with manifest status

### Acceptance Criteria

- [x] Remove the aggregation logic, code reference: https://github.com/kyma-project/lifecycle-manager/blob/407b873a1d7f3de86446b193e1f772dec3f45f0c/internal/declarative/v2/reconciler.go#L389
- [x] Adjust existing tests aligned with this new requirement
- [x] synchronised with Busola team so that all the states are displayed correctly

### Feature Testing

Unit tests, Integration tests, End-to-End tests

#### required e2e tests:
1. test module CR state not affect manifest CR
**Given** **Template Operator ModuleTemplate** on the **KCP Cluster**
**And** the **Sample CR** final state has been configured as `Warning`
**When** the **Template Operator Module** is enabled
**Then** the **Manifest CR** should be in `Ready` state
**Then** the **Sample CR** should be in `Warning` state

2. test the module Deployment failing state propagated into manifest CR
**Given** **Template Operator ModuleTemplate** on the **KCP Cluster**
**When** the **Template Operator Module** is enabled
**And** the **Template Operator Deployment** configured in error state
**Then** the **Manifest CR** should be in `Error` state
**Then** the **Sample CR** should be in `Ready` state

**Comment by c-pius** [comment]
Re-opened this as we have noticed undesired behavior during verification on STAGE. We can observe that the state in `ManifestCR` is separated from `DefaultCR` ✅ 

However, we also noticed that on initial installation, `ManifestCR` and therefore also `KymaCR` go first to `Error` state before becoming `Ready`. Previously, this has been `Processing` instead of `Error` for the transient initializing state.

**Comment by c-pius** [comment]
### Some observations:

- ManifestCR state goes Processing->Error->Processing. If second processing is not reached within 5s, it stays in error for 5 mins.
- ManifestCR sometimes transitions Processing before the Deployment is ready

### Reproduce on local test cluster:

It seems to be possible to reproduce the behavior on local test cluster by enabling template-operator and directly deleting it's deployment once it turns up. Using some debug logs the following was observed. `setManifestState` is entered with `status: Error` (coming from ManifestCR) and `state: Error` (coming from the deployment). As both status match, we are exiting the function returning `nil`. In consequent execution, `finishReconcile` exited with a successful requeue.

Logs haven't revealed yet how it initially transitioned to error states. Will be further investigated

**Comment by c-pius** [comment]
## Questions regarding the implementation

- a) can we code an explicit error exit when `state: Error` (similar to when `state: Processing`)?
- b) is the implementation of [`GetPodsState`](https://github.com/c-pius/lifecycle-manager/blob/main/internal/manifest/ready_check.go#L89-L106) correct? Shouldn't it be returning `Ready` only if all pods are in ready state?

**Comment by c-pius** [comment]
Related ADR: https://github.com/kyma-project/lifecycle-manager/issues/1706

**Comment by c-pius** [comment]
Follow-up created to implement the ADR: https://github.com/kyma-project/lifecycle-manager/issues/1719
