### ISSUE TITLE
Drop alert rules for old reconciler

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1579]
### Description

We were pinged on 2024-05-24 wrt. to an alert coming for two Kymas on prod with Reconciliation Failures. It turned out that both were deprovissioned successfully, but old reconciler still tried to reconcile them.

Since support for old reconciler has been dropped, we should consider also dropping the related alert rules.

See internal issue 5584.

### Reasons

Avoid alerts that we will not take care of any longer

### Acceptance Criteria

- [x] no more alert rules for old reconciler

**Comment by nesmabadr** [comment]
Checked with the SREs, the alert rules for the old reconciler were already removed on the 6th of June
