### ISSUE TITLE
Kyma module as OCM component

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1587]
Created on 2024-05-28 by Xin Ruan (@ruanxin)

## Decision log

| Name               | Description            |
| ------------------ | ---------------------- |
| Title              | Kyma module as OCM component     |
| Due date           | 2024-06-30             |
| Status             | Proposed on 2024-05-28 |
| Decision type      | Binary                 |
| Affected decisions | -                      |
 
## Context
To ensure efficient deployment of all Kyma Control Plane (KCP) components and Kyma modules across multiple KCP landscapes, we will adopt the Open Component Model (OCM) as the standard for describing these components. This standardization will facilitate consistent delivery and management of software bills of delivery (SBOD) for KCP components.

## Decision:
Each Kyma module will be defined as an OCM component. This involves specifying several required and optional OCM resources for each module.

### Naming convention
Prefix each module with `kyma-project.io/module/` followed by the module's short name to comply with the OCM component [naming pattern](https://github.com/open-component-model/ocm/blob/7a913dc51ebc2f8db714d99a8e061017ee71ae01/resources/component-descriptor-ocm-v3-schema.yaml#L56).

### OCM Resources Definition
The following table describes the required and optional resources for each Kyma module:
| Resource Name               | Type            | Definition |
| ------------------ | ---------------------- |  ---------------------- |
| default-cr | directory  | `[Required]` the module Default CR, provided by module team in github release as assets, e.g: in this keda-manager [release](https://github.com/kyma-project/keda-manager/releases/tag/1.1.0), it's [keda-default-cr.yaml](https://github.com/kyma-project/keda-manager/releases/download/1.1.0/keda-default-cr.yaml) |
| raw-manifest | directory | `[Required]` the module resources, provided by module team in github release as assets, e.g: in this keda-manager [release](https://github.com/kyma-project/keda-manager/releases/tag/1.1.0), it's [keda-manager.yaml](https://github.com/kyma-project/keda-manager/releases/download/1.1.0/keda-manager.yaml) |
| all module image name | ociArtifact | `[required]` All module images, including those managed by the module, each image is a dedicated ociArtifact resource |
| associated-resources | plainText | `[optional]` for those managed module which have managed resources, provided by module team in github release as assets, this content will be the source of truth for providing the `associatedResources` field in module configuration, check an example for keda module [here](https://github.com/kyma-project/community-modules/blob/main/modules.js#L181-L187) |
| localization | plainText | `[optional]` to be compatible with [ocm-controller](https://ocm.software/docs/controller/architecture/), we provided this additional localization `ConfigData` resource for localization purposes, for the detailed usage, check the ocm-controller [document](https://github.com/open-component-model/ocm-controller/blob/26d4a58d201db7ef2c25a9f6179f8b12606eed71/docs/architecture.md#localization-controller) |

### Kyma Module Deployment resources
To ensure the Kyma Lifecycle Manager (KLM) can replace localized module images during deployment, all required images must be listed in the Module Operator Deployment Kubernetes resource. Images are categorized into two groups:
- **module operator images**: All the images listed in module `Deployment` as container images.
- **module managed images**: Images deployed by certain module managers during runtime, for example, btp-manager will deploy [sap-btp-service-operator](https://github.com/kyma-project/btp-manager/blob/a59f2cd89943b286af167db55a6a1cfe1e360170/module-resources/apply/deployment.yml#L55), for this kind of usages, each image must be provided in module `Deployment` as a dedicated container env value.

All images must be published and signed in the central image registry: `europe-docker.pkg.dev/kyma-project/prod`

## Consequences:
Adopting this approach will streamline the deployment process, enhance consistency across different environments, and provide a clear structure for managing module resources. It will also support localization needs and integration with KLM or existing OCM tools.

**Comment by ruanxin** [comment]
an example:
```
ocm get resource ghcr.io/ruanxin/kcp-source//kyma-project.io/module/keda -c 1.2.0 -owide
NAME         VERSION IDENTITY TYPE        RELATION ACCESSTYPE  ACCESSSPEC
default-cr   1.2.0            PlainText   local    localBlob   {"localReference":"sha256:d2fe1bc4baa3dc70a324046b038fa03832fdb9e68a47a7e976987b3f1ea36b08","mediaType":"application/octet-stream"}
module-image 1.2.0            ociArtifact external ociArtifact {"imageReference":"europe-docker.pkg.dev/kyma-project/prod/keda-manager:1.1.0"}
raw-manifest 1.2.0            Directory   local    localBlob   {"localReference":"sha256:65d799625d4b97364d4d316c806365e12cb79398fbe1b3ec48eed2a36282c3ed","mediaType":"application/x-tar"}
```

**Comment by pbochynski** [comment]
lgtm
