### ISSUE TITLE
Use OCM as software bills of delivery (SBOD) for KCP components and Kyma modules

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1588]
Created on 2024-05-28 by Xin Ruan (@ruanxin)

## Decision log

| Name               | Description            |
| ------------------ | ---------------------- |
| Title              | Use OCM as software bills of delivery (SBOD) for KCP components   |
| Due date           | 2024-06-30             |
| Status             | Proposed on 2024-05-28 |
| Decision type      | Binary                 |
| Affected decisions | https://github.com/kyma-project/lifecycle-manager/issues/1587, https://github.com/kyma-project/lifecycle-manager/issues/1605 |
 
## Context
To ensure efficient deployment of all Kyma Control Plane (KCP) components and Kyma modules across multiple KCP landscapes, we will adopt the Open Component Model (OCM) as the standard for describing these components. This standardization will facilitate consistent delivery and management of software bills of delivery (SBOD) for KCP components.

## Decision:
All KCP components and Kyma modules will be represented and published as OCM components, which can be referenced using an aggregated OCM component.

### OCM components:
<img width="469" alt="image" src="https://github.com/kyma-project/lifecycle-manager/assets/2189071/e0ba6e06-57f1-48ae-aa56-db7103186ea6">

| OCM component name | Definition |
| ------------------  |  ---------------------- |
| `kyma-project.io/kcp`   | Represents a deliverable SBOD that references all KCP components and Kyma modules. |
| `kyma-project.io/module/*`  | Represent kyma module, same as the current full qualified domain name of Kyma module (`*` means Kyma module short name), the detailed definition can be found in this decision record https://github.com/kyma-project/lifecycle-manager/issues/1587 |
| `kyma-project.io/kcp/*`   | Represent kcp component, e.g: lifecycle manager will be `kyma-project.io/kcp/klm`, the detailed definition can be found in this decision record https://github.com/kyma-project/lifecycle-manager/issues/1605 |

### Channel as OCM extra Identity to Kyma Module OCM component
For Kyma modules released in specific channels, an extra identity `channel` will be introduced, containing the expected channel as its value.

### Example
In the following example, it has `kyma-project.io/kcp` with version `1.6.0` published in OCI registry `ghcr.io/ruanxin/kcp-source`. It includes various Kyma modules and KCP components(not a complete list).
- ` kyma-project.io/module/istio` is released in both `fast`  and `regular` channels with version `1.6.0`
- ` kyma-project.io/module/istio` also released with version `1.5.0` which allow users to choose additionally besides subscribing to a specific channel.
- ` kyma-project.io/module/btp` is released version `1.1.8` in `fast` and `1.1.7` in `regular` channel
- It contains KCP component `kyma-project.io/kcp/klm`, `kyma-project.io/kcp/kyma-environment-broker`
```
╰─⠠⠵ ocm get references ghcr.io/ruanxin/kcp-source//kyma-project.io/kcp -c 1.6.0 -o wide
NAME                    COMPONENT                                   VERSION IDENTITY
btp                     kyma-project.io/module/btp                  1.1.8   "channel"="fast","name"="btp"
btp                     kyma-project.io/module/btp                  1.1.7   "channel"="regular","name"="btp"
istio                   kyma-project.io/module/istio                1.6.0   "channel"="fast","name"="istio"
istio                   kyma-project.io/module/istio                1.6.0   "channel"="regular","name"="istio"
istio                   kyma-project.io/module/istio                1.5.0   "name"="istio"
klm                     kyma-project.io/kcp/klm                     0.1.2   "name"="klm"
kyma-environment-broker kyma-project.io/kcp/kyma-environment-broker 1.5.6   "name"="kyma-environment-broker"
```

## Consequences:
- Ensures consistent and efficient delivery of KCP components.
- Simplifies the management and tracking of components through OCM.
- Enables clear versioning and channel-specific releases.
- Provided as the single source of truth for module configuration list, as an example [here](https://github.com/kyma-project/community-modules/blob/e288a449b773a23e0d780e15281cdfa690aa3c4c/modules.js#L1)

**Comment by pbochynski** [comment]
lgtm
