### ISSUE TITLE
Rename `AvailableModule`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1638]
### Description

`Kyma` struct has the method [`FetchAvailableModules()`](https://github.com/kyma-project/lifecycle-manager/blob/2fed199d47f5166a26c11cd524d5671052f53aa0/pkg/templatelookup/availableModules.go#L38C49-L38C64) returning an `AvailableModule` struct which basically is a `Module` accompanied by an `enabled` flag. It basically lists all from KymaCR Spec and Status and adds the info if enabled (in Spec) or disabled but still there (not in Spec, but still in Status).

Personally, I find the term "Available" highly confusing/misleading here. I would have expected something related to the modules available in the module catalog.

We need to refactor this and come up a proper name or avoid the explicit naming altogether.

### Reasons

Confusing naming makes it hard to understand and reason about the code.

### Acceptance Criteria

- [x] Consider renaming only or refactor the `AvailableModule` type holistically to make it more explicitly understandable and self-explanatory 
- [x] If refactoring is considered make it somehow explicit to indicate usage as DTO
- [x] #2140

**Comment by medmes** [comment]
As a follow up ticket: #2140 , this ticket include the proposed improvement of refactoring of the `templatelookup` package and it's dependency.
