### ISSUE TITLE
Remove other ways of module referencing in existing Kymas

### ISSUE THREAD

**Issue by amritanshusikdar** [kyma-project/lifecycle-manager#1682]
### Description

_Follow-up to dropping multiple ways of referencing modules (#1521)_

There is a possibility that existing Kymas in production systems might still be using the deprecated ways (NamespacedName/FQDN) to reference modules. Here is the [implementation](https://github.com/kyma-project/lifecycle-manager/pull/1672), which allows only using the label value name to successfully reference the modules in the Kymas. 

However, before the implementation could be applied, it has to be made sure that no other Kyma is still relying on the deprecated ways.

### Reasons

This is a pre-requisite for the successful deprecation of other ways to reference modules in Kymas, and to have the label module name as the only acceptable method.

### Acceptance Criteria

- [ ] Every Kyma in the SKR clusters uses the label `operator.kyma-project.io/module-name` module name to reference their respective modules
- [ ] Verification of every Kyma on KCP (all landscapes) that status.modules has only qualified name entries
- [ ] 
   - Status of Kyma CRs in the KCP could be of some help

**Comment by nesmabadr** [comment]
Referencing modules using their FQDN or namespace/name is currently not possible (since 4 months at least), since we have the module name as a label in the Manifest and this produces an ssa error because the label shouldn't have a "/". So this issue can be closed.
