### ISSUE TITLE
Avoid SSAs for mandatory module Manifest CRs

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1687]
### Description

Follow up to https://github.com/kyma-project/lifecycle-manager/issues/1456

a) check if there can be a shared implementation for regular and mandatory modules to avoid SSAs, or if a individual implementation is necessary
b) decide with the team whether the effort for a shared or individual implementation is reasonable (we only have one mandatory module at the moment, might not be worth the effort)
c) if so, create a follow up ticket that either proposes the shared implementation or proposes a individual implementation

Please keep in mind to not introduce the mandatory modules into the KymaCR Status. The mandatory modules should be fully hidden from the customer.

### Reasons

In above ticket we significantly improved the KLM load by applying SSAs to regular manifests only if we have differences in `Channel, Version, or State`. We have not implemented the same for mandatory modules yet since we don't have a state for mandatory modules in the KymaCR (needed for the check) and at the same time didn't want to create completely diverging implementations for mandatory modules.

### Acceptance Criteria

- [ ] **Time-boxed Research**: 1 day
- [ ] possible implementations evaluated
- [ ] decision taken with the team
- [ ] follow up created

**Comment by ruanxin** [comment]
mandatory module use same logic to sync manifest CR https://github.com/kyma-project/lifecycle-manager/blob/03a80f5d300ea5fe2e343a7c1756b650ed173ef5/internal/controller/mandatorymodule/installation_controller.go#L79

**Comment by ruanxin** [comment]
```
╭─in ~ 24-09-20 - 10:44:33
╰─○ k get manifest -n kcp-system 0c979a42-f521-41d8-b5ee-eabbaff6abd1-warden-641595061 -w -oyaml | grep resourceVersion
  resourceVersion: "7470949524"
^C
╭─3 in ~ 24-09-20 - 10:51:12
```

wathed one Warden manifest CR, haven't get updated within reconcile schedule.
