### ISSUE TITLE
Create subfolders for `/docs/user` and `/docs/contributor`

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/lifecycle-manager#1712]
**Description**

Lifecycle Manager, in general, is not an end-user-facing project. Most of the documents are relevant only to those who contribute to the project; however, some documents are directed to its users.

To have a clear division of the roles we could split the `/docs` folder into `/docs/user` and `/docs/contributor`.

We had a case when the SRE team could not understand why the spec of a Kyma CR was different in the KCP and SKR. These were very technical details that were not explained in the `Kyma CR` documentation as they are not important to the users of Lifecycle Manager. However, the `/docs/contributor` folder could be the right location for that kind of information.

Also, looking at the folder structure of other `kyma-project` repositories developed by other Kyma teams, especially modules, the split into `/docs/user` and /`docs/contributor` is the template convention accepted and widely used by most of them.

**TBD:** The open question is how to categorize individual documents and define their final location (user vs. contributor).

**Reasons**

More transparent project documentation.

**Assignees**

@kyma-project/technical-writers
@kyma-project/jellyfish 

**Attachments**

**Comment by c-pius** [comment]
We may take this also as an opportunity to clearly defining our target groups. E.g., user: the end user of a Kyma runtime; contributor: developer or SRE (may be SAP internal or external). We also noted this here: https://github.com/kyma-project/lifecycle-manager/issues/1447

**Comment by c-pius** [comment]
As part of this refactoring and addressing new personas, we may consider to get rid of docs which seem to be obsolete anyway, i.e.:

- https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/prepare-gcr-registry.md
- https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/provision-cluster-and-registry.md
- https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/starting-operator-with-webhooks.md

**Comment by mmitoraj** [comment]
Initial evaluation: 
- [ ] [config-private-registry.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/config-private-registry.md) - **user**
- [ ] [local-test-setup.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/local-test-setup.md) - **user**
- [ ] [prepare-gcr-registry.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/prepare-gcr-registry.md) - ❌ to be removed
- [ ] [provision-cluster-and-registry.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/provision-cluster-and-registry.md) - ❌ to be removed
- [ ] [starting-operator-with-webhooks.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/starting-operator-with-webhooks.md) ❌ to be removed
- [ ] [api/README.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/README.md) - **user**
  - [ ] [changelog.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/changelog.md) - **contributor** ? 
  - [ ] [kyma-cr.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md) - **user**
  - [ ]  [manifest-cr.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/manifest-cr.md) - **user**
  - [ ] [moduleTemplate-cr.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md) **user**
- [ ] [architecture.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/architecture.md) - basics in the `user/README.md`, details in **contributor**
- [ ] [controllers.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/controllers.md) - basics in the `user/README.md`, details in **contributor**
- [ ] [running-modes.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/running-modes.md) - **user**
- [ ] [01-10-control-plane-quick-start.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/user-tutorials/01-10-control-plane-quick-start.md) - ❌ to be removed
- [ ] [02-10-manage-module-with-custom-resource-policy.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md) - **user**
- [ ] [modularization.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/modularization.md) - **contributor**
- [ ] [/internal/declarative/README.md](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/declarative/README.md) - **contributor**
- [ ] [internal/manifest/README.md](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/manifest/README.md) - **contributor**

**Comment by mmitoraj** [comment]
As for now, we have only one doc dedicated both for the user and module provider maybe we could merge that persona into one general user.

**Comment by mmitoraj** [comment]
I would like to start referring to CRDs instead of APIs

**Comment by c-pius** [comment]
> [moduleTemplate-cr.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md) contributor

Not sure if relevant when reviewing downstream, but ModuleTemplate is also relevant for module-developer role (and neighbours team).

**Comment by mmitoraj** [comment]
Create a glossary explaining some terms, for example:
- Synchronized remote cluster
- Control Plane
- ...
