### ISSUE TITLE
Increase Kyma worker on PROD

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1725]
### Description

Based on Plutono metrics, there is around 20s delay of Kyma CR reconcliation. The reason is we haven't configure enough worker to handle current amount of Kyma CR.

### Reasons

Affect user experience.

### Acceptance Criteria

- [ ] double the amount of kyma worker to 50
- [ ] if the latency is not improved, and CPU usage also not affect hugely, increase the amount of Kyma worker until there is no significant latency appears.

**Comment by c-pius** [comment]
Since we saw some improvements of the latest changes on STAGE (1.1.1), we are going to wait until this release is deployed to prod. From there, we can determine if we want to increase Kyma workers (and may decrease Manifest workers).
