### ISSUE TITLE
Investigate and Analyze Impact of Reconciler Operator Changes in KCP CLI and create Action / Communication Plan for Changes

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#177]
**Description**

Clarify with SRE if there is still a need to support the KCP CLI in the new reconciler architecture.

AC:
* Agreement with SREs whether we upgrade KCP CLI or not (if yes, define commands which will still be support in the new reconilcer)

**Comment by tobiscr** [comment]
|Command|Purpose|Workaround without KCP CLI|
|--|--|--|
|`kcp rc`|List all reconciliations|Use `kubectl` to retrieve Kyma CRDs and check their status|
|`kcp rc debug`|Enable the debug mode for a reconciliation|Use `kubectl` and set `debug` field to true in Kyma CR ([see issue](https://github.com/kyma-project/lifecycle-manager/issues/79))|
|`kcp rc disable`|Disable the reconciliation for a Kyma instance|? TBC ?|
|`kcp rc enable`|Enable the reconciliation for a Kyma instance (which was previously disabled)|? TBC ?|
|`kcp rc info`|Show details of a reconciliation|Use `kubctl` to retrieve all module CRs and check their status|

**Comment by tobiscr** [comment]
@ebensom : would be great if you could quickly verify if the commands which are marked with `? TBC ?` are still required. Otherwise we would stop supporting them in the new reconciler architecture.

**Comment by ebensom** [comment]
`kcp rc operation stop`: not needed

`kcp rc enable/disable`: we used this occasionally during troubleshooting. Examples: verify if reconciler keeps patching a resource when it shouldn't, temporarily stop reconciliation to verify if a change could resolve / mitigate the issue. 
However I understand it would be cumbersome to implement it for each module operator (be it local or central) to have a "suspend" attribute in the CR which would make the operator to not reconcile the CR. Furthermore wou don't want to expose such functionality on the SKRs for users for obvious reasons :)

I would say let's not plan support for enable/disable reconciliation in module operators.

**Comment by janmedrek** [comment]
Since @ebensom mentioned that in-cluster Module Operators should be excluded, for now, I've created a follow-up for disabling the whole cluster from the overall reconciliation process: https://github.com/kyma-project/lifecycle-manager/issues/315

Will close this issue now as the progress will be tracked in the new one. Should we need the possibility to disable specific Module Operators as well we can create more issues depending on what and where is needed.
