### ISSUE TITLE
use consistent fqdn for moduletemplate and update outdated moduletemplate file

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1774]
Atm, we still have tests use outdated fqdn for `kyma-project.io/template-operator` moduletemplate, which makes tests difficut to understand and maintain. 

e.g:

1. in test:
https://github.com/kyma-project/lifecycle-manager/blob/158fa52f49cac0fa01827b8d4e6821cc1067b311/tests/integration/controller/mandatorymodule/deletion/controller_test.go#L42
2. in outdated moduletemplate:
https://github.com/kyma-project/lifecycle-manager/blob/03a80f5d300ea5fe2e343a7c1756b650ed173ef5/tests/moduletemplates/operator_v1beta2_moduletemplate_kcp-module.yaml#L21

AC:
- [x] replace outdated moduletemplate which use `kyma-project.io/template-operator`
      - `operator_v1beta2_moduletemplate_kcp-module.yaml` is used for [generate moduletemplate](https://github.com/kyma-project/lifecycle-manager/blob/03a80f5d300ea5fe2e343a7c1756b650ed173ef5/pkg/testutils/builder/moduletemplate.go#L137) for integeration tests, it should be replaced with `moduletemplate_template_operator_v1_regular.yaml`
      -  `operator_v1beta2_moduletemplate_kcp-module-cred-label.yaml` is used for testing `oci-registry-cred` label, update it with new ocm component descriptor (requires a push to oci registry)
      -  `operator_v1beta2_moduletemplate_kcp-module_updated.yaml` is used [here](https://github.com/kyma-project/lifecycle-manager/blob/aa0cd12d84ac9411f4f71c3564831f0da56e2e97/tests/integration/controller/kyma/manifest_test.go#L65), replace it with moduletemplate which is used for e2e test for update test.
      - `operator_v1beta2_moduletemplate_ocm.software.v3alpha1.yaml` is for testing ocm schema v3alpha1, use kyma cli generate a new version with correct fqdn (requires a push to oci registry)
      - push newly generated artefacts
- [x] adjust tests which use `kyma-project.io/template-operator`, replace it with `kyma-project.io/module/template-operator`, define a const fqdn name for sharing the usage among tests.

**Comment by LeelaChacha** [comment]
- `operator_v1beta2_moduletemplate_kcp-module.yaml` already got replaced by `v1beta2_template_operator_current_ocm.yaml`, which contains the current fqdn
- `operator_v1beta2_moduletemplate_kcp-module_updated.yaml` was already removed
- `operator_v1beta2_moduletemplate_ocm.software.v3alpha1.yaml` was already removed
