### ISSUE TITLE
Load Test for demo scenario for >10k Clusters

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#18]
Implement a demo load test scenario, verify if the load test setup works as expected.

This task mainly have three parts:
## 1. Load test script
- [x] Written as k6 script, a demo can be found here: https://github.com/ruanxin/performance-test/blob/main/load_generator.js
    - [x] Load test the remote watching: watch resources on X remote clusters and ensure the reported customer changes are properly tracked and considered by the Kyma Operator.
    - [x] **TBC - done by PB already?**: Implement test case to measure the amount of maximal watchable resources until K8s starts to deliver not all change events anymore => sync with @ebensom about limitations SREs wre already facing in their setup

## 2. Target Cluster under testing
- [x] Provision 2 Gardener clusters, one as [control plane](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-jellyfish/shoots/ctrlplane/), one as [skr cluster](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-jellyfish/shoots/worker1/)
- [x] Deploy [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) into control plane cluster
- [x] Create a grafana dashboard, with some demo panel to monitor some predefined metrics
- [x] Create a helm chart to define a dummy resource which simulate the behavior of resources defined in kyma components
  - https://github.com/ruanxin/performance-test/tree/main/kyma-load-test
- [x] Deploy kyma-operator, manifest-operator into control plane cluster
- [x] Deploy skr-operator into skr cluster which manage the reconciliation of target resources
- [x] Config a remote OCI registery to save component descriptor files
- [x] Run load test against control plane cluster, target 10000 kyma with 200000 modules
  - [x] ⛔ ~10% of the modules should be kcp modules~ NO kcp modules planned for Phase 1

## 3. Conclusion
- [x] Present measuring / results to team => point out identified threshold

## 4. Findings and followup issue
- [ ] kyma-project/lifecycle-manager#266
- [x] kyma-project/module-manager#141
- [x] ⛔ https://github.com/kyma-project/module-manager/pull/134
- [ ] https://github.com/kyma-project/lifecycle-manager/pull/283
- [ ] https://github.com/kyma-project/lifecycle-manager/pull/277
- [x] https://github.com/kyma-project/lifecycle-manager/pull/284
- [x] https://github.com/kyma-project/lifecycle-manager/pull/282
- [x] https://github.com/kyma-project/lifecycle-manager/pull/276
- [x] https://github.com/kyma-project/lifecycle-manager/pull/273
- [x] https://github.com/kyma-project/lifecycle-manager/pull/270
- [x] https://github.com/kyma-project/module-manager/pull/145
- [x] https://github.com/kyma-project/module-manager/pull/140
- [x] https://github.com/kyma-project/module-manager/pull/134
- [x] https://github.com/kyma-project/module-manager/pull/132

## Notes
- Rewrite manifest-operator to overwrite deployed helm chart resource name with kyma CR name as suffix
  - `operator/internal/pkg/prepare/deploy.go:106`
  - make sure the overwritten name is an unique identifier
- Load test should not run until listener, watcher integrated

**Comment by tobiscr** [comment]
Depends on https://github.com/kyma-project/runtime-watcher/issues/70

**Comment by tobiscr** [comment]
Waiting for https://github.com/kyma-project/lifecycle-manager/issues/200

**Comment by jakobmoellersap** [comment]
Closing as only minor follow-ups need to be closed main round of load tests are considered complete
