### ISSUE TITLE
Label the `kube-system` namespace with `managed-by` label

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1824]
### Description

Similarly to `istio-system` and `kyma-system` namespaces, we should treat the `kube-system` namespace with the `managed-by` label.

### Reasons

This will indicate that `kube-system` namespace should not be interacted with by the user.

It will also simplify filtering out traces/logs.

### Acceptance Criteria

- [ ] `kube-system` namespace is labelled with the `operator.kyma-project.io/managed-by=kyma` label

**Comment by janmedrek** [comment]
Blocked by: https://github.com/kyma-project/lifecycle-manager/issues/1821

**Comment by ruanxin** [comment]
we have a decision that kyma infrastructure manager takes responsibility for labeling it.
