### ISSUE TITLE
[ModuleCatalog] Add `.spec.resources` to ModuleTemplate

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1842]
### Description

In https://github.com/kyma-project/lifecycle-manager/issues/1681 it has been decided to add `resources` to ModuleTemplates. We need to update the ModuleTemplate to include this information.

The information shall look as follows:

```yaml
spec:
  resources:
  - name: <string>
    link: <link>
```

`spec.resources` is OPTIONAL (for compatibility reasons). The items in a resources entry are REQUIRED.

### Reasons

Enables CLI and dashboard to support in the manual installation of a module by downloading the needed resources and applying them to the cluster.

### Acceptance Criteria

- [x] `.spec.resources` added to ModuleTemplate
- [x] Added an entry to https://github.com/kyma-project/lifecycle-manager/issues/776 that `.spec.resources` must be added as required in a future major API version

**Comment by janmedrek** [comment]
@c-pius wouldn't something like `.spec.rawManifest` make it more transparent what that section really stands for?

I am just questioning the naming, I would make sure it is self-explanatory when looking at the resource without the use of Busola.

**Comment by c-pius** [comment]
@janmedrek sorry, your comment slipped through while I was on vacation. Actually, `.spec.resources` is a list of named items with a download link. Indeed, it is intended that this list contains the entry `rawManifest`. We chose to go for this "list container" instead of a direct `.spec.rawManifest` field so that we can add further resources in the future without doing additional API changes.

So it would look like:

![Image](https://github.com/user-attachments/assets/d4bd716f-0e87-4508-a23b-2aa98f0976d0)
