### ISSUE TITLE
[ModuleCatalog] Implement Logic for `ModuleReleaseMeta` CRD in Kyma Reconcile Loop

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1849]
### Description:
We need to implement the logic to utilize the [newly created `ModuleReleaseMeta` CRD](https://github.com/kyma-project/lifecycle-manager/issues/1848) in the Kyma reconcile loop. Currently, we fetch and filter `ModuleTemplates` based on the channel specified in `ModuleTemplate.spec`. This logic needs to be updated to fetch the appropriate `ModuleTemplate` by using the information from the `ModuleReleaseMeta` CRD.

Detailed decision ticket: https://github.com/kyma-project/lifecycle-manager/issues/1815

### New Logic:
- In the Kyma reconcile loop:
  - Instead of fetching all `ModuleTemplates` and filtering by the channel specified in `ModuleTemplate.spec`, first fetch the `ModuleReleaseMeta` CR.
  - Use the channel specified in the `Kyma.spec` for the module.
  - Then, check the corresponding version from the `ModuleReleaseMeta.spec`.
  - Fetch the matching `ModuleTemplate` based on this version.
- Introduce a naming pattern for `ModuleReleaseMeta` to simplify the fetching process, it needs to be well-documented (just the module name).
  - Use the naming pattern for `ModuleTemplate` CRs as well (modulename-versionnumber)

### Acceptance Criteria:
- [x] Adapt the current implementation to follow the new logic of using `ModuleReleaseMeta` for fetching `ModuleTemplates`.
- [x] Adapt all relevant tests to reflect this new functionality.
- [x] Adapt existing documentation and add new feature documentation explaining the usage of `ModuleReleaseMeta`, including any naming patterns introduced.

**Comment by c-pius** [comment]
> ModuleReleaseMeta CRs should be cached using a TTL cache

Can we really cache it? When it changes, we enqueue a reconcile event for the related kymas which should then fetch the up to date version, and not a maybe outdated one from the cache

> Consider introducing a naming pattern for ModuleReleaseMeta to simplify the fetching process. If this is decided upon, the naming pattern needs to be well-documented.

I think the naming pattern must already be defines as part of https://github.com/kyma-project/lifecycle-manager/issues/1848. But I think it can be as simple as the module name?

**Comment by janmedrek** [comment]
Depends on: https://github.com/kyma-project/lifecycle-manager/issues/1848

**Comment by nesmabadr** [comment]
Verified this on dev, since no modules use the modulereleasemeta yet.
