### ISSUE TITLE
[Module Catalog] Remove the ModuleTemplate name overwrite in E2E tests for ModuleReleaseMeta

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1956]
### Description

Right now in the E2E tests which are run with ModuleReleaseMeta, we have a step to overwrite the name of the ModuleTemplate to be `moduleName-version`. We need to remove this overwrite after the modulectl allows the creation of ModuleTemplate with the new name format and the E2E tests workflows are actually using the modulectl not the Kyma CLI.

### Acceptance Criteria

- [ ] Use the modulectl to regenerate E2E ModuleTemplate
- [ ] yamls should be re-generated (https://github.com/kyma-project/lifecycle-manager/tree/main/tests/moduletemplates)

**Comment by ruanxin** [comment]
blocked by   https://github.com/kyma-project/modulectl/issues/98
