### ISSUE TITLE
[Module Catalog] Create concept for how to deal with mandatory modules and the latest module changes

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1979]
## Description

We need to create a concept for how we deal with mandatory modules going forward with the latest changes

- will mandatory modules have module release meta?
- what should be the naming scheme for mandatory module?

## AC

- [x] prepared an E2E concept for mandatory modules using new module templates

**Comment by nesmabadr** [comment]
Mural board for discussion: https://app.mural.co/t/sappm1454/m/sappm1454/1732614892093/9ce542df2ffb6af9ab192789ecb75313beb39f68
Created an issue as a followup: https://github.com/kyma-project/lifecycle-manager/issues/2068
