### ISSUE TITLE
[Research] make rate limiting works as expected

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#2026]
The requeue metrics we observed in plutono dashboard is `manifest_sync_resources - unexpected`, which is requeued by following code in manifest reconciler, and should be guarded by rate limiting.

https://github.com/kyma-project/lifecycle-manager/blob/aaf6b0b0c618efafd89e0b4434982dd06e369c85/internal/declarative/v2/reconciler.go#L539-L542

The rate limiter we configured for manifest reconciler:
https://github.com/kyma-project/lifecycle-manager/blob/401ee8304608d740a83f6370b8488b96a39f154a/internal/rate_limiter.go#L11-L19

The parameter configured for the production landscape
```
- --failure-max-delay=30s
- --failure-base-delay=5s
- --rate-limiter-burst=2000
- --rate-limiter-frequency=1000
```
Based on the configuration, we should expected error item requeued with 5s interval, then increase exponentially to maximum 30s, however, it seems not the fact, the error item will requeued immediately.

**AC**
- [ ] research and find the root cause why the current setup is not working, in case it's a bug internally from controller-runtime, propose an alternative approach.
- [ ] use shared rate limiter code for manifest and kyma reconcociler, they currently use same configuration.
https://github.com/kyma-project/lifecycle-manager/blob/ed7ea6355ffe1d4067b42ece462b055376ec5933/cmd/main.go#L282 

**Attachements**
https://danielmangum.com/posts/controller-runtime-client-go-rate-limiting/

**Comment by LeelaChacha** [comment]
@ruanxin 

I performed an experiment with the following steps:
1. Log the start of reconciliation for manifest
2. Force the reconcile loop to return ctrl.Result{}, fmt.Errorf("test error")
3. Deploy template-operator to SKR
4. Observe Logs

With the control-plane kustomization of base delay of 5s and max delay of 30s, I observed the reconciliation time stamps were actually separated by 5s, 10s, 20s, 30s, 30s, 30s ....

```
2024-12-11T02:51:18.816658215Z Start of reconcile kyma-sample-template-operator-2235966007
2024-12-11T02:51:23.824828884Z {"level":"ERROR","date":"2024-12-11T02:51:23.824428926Z","caller":"controller/controller.go:316","msg":"Reconciler error"...
...
2024-12-11T02:51:23.824309926Z Start of reconcile kyma-sample-template-operator-2235966007
2024-12-11T02:51:23.824828884Z {"level":"ERROR","date":"2024-12-11T02:51:23.824428926Z","caller":"controller/controller.go:316","msg":"Reconciler error"...
...
2024-12-11T02:51:33.826538166Z Start of reconcile kyma-sample-template-operator-2235966007
2024-12-11T02:51:33.826807125Z {"level":"ERROR","date":"2024-12-11T02:51:33.826536416Z","caller":"controller/controller.go:316","msg":"Reconciler error"...
...
and so on...
```

The rate limiter seems to work in local testing. I need more information about how to recreate the behaviour that you mentioned on the production landscape.

**NOTE:** The ItemExponentialFailureRateLimiter limits the requeues on per-manifest basis. Could it be that the increase in the `manifest_sync_resources - unexpected` metric that you observed came from different manifests, making it seem as one manifest is requeuing immediately?

**Comment by ruanxin** [comment]
it's good to have this finding to prove it's working.
> The rate limiter seems to work in local testing. I need more information about how to recreate the behaviour that you mentioned on the production landscape.

The next step what you can do is enable more modules, to see if the rate limiter still works as expected. The thing is when `manifest_sync_resources - unexpected` happens, see below between 11/12 - 11/13, the amount of manifest in Error State doesn't have significant change, the recorded Error manifest CR on average is just 2 during that time. So it's not the assumption you mentioned in the NOTE.

![image](https://github.com/user-attachments/assets/2731de13-0d55-4573-a1aa-ac52b14f4fbf)
![image](https://github.com/user-attachments/assets/591a0e16-fb50-46f0-9eec-80a0eb207d02)

**Comment by LeelaChacha** [comment]
UPDATE: With two modules, the rate-limiting works as expected for both modules. The individual module's delays are also independent, meaning they both follow the pattern of 5s, 10s, 20s, 30s, and 30s... irrespective of how the two modules' requeue overlap. I experimented with one failing module and a second failing module enabled later on, as well as both modules failing together. The individual requeue times always followed the sequence. Therefore, the NewTypedItemExponentialFailureRateLimiter seems to be working properly. 

I think that either something has changed in the code since the creation of this issue, or it is invalid to conclude that the rate limiter is not working based on the kyma requeue metric. The high number of requeues do not explicitly point to an immediate requeue of the module. The settings on prod would also allow up to 120 requeues for one module in one hour. (60 minutes x (60s/30s delay)), which is much less than what we can observe in the screenshot. Therefore, I believe that we cannot conclude that the module is being requeued immediately based on this metric

**Comment by ruanxin** [comment]
>The high number of requeues do not explicitly point to an immediate requeue of the module. The settings on prod would also allow up to 120 requeues for one module in one hour. (60 minutes x (60s/30s delay)), which is much less than what we can observe in the screenshot. Therefore, I believe that we cannot conclude that the module is being requeued immediately based on this metric

I'm not sure if I get your point clearly, but as you mentioned, for one module it's only 120 requeue possible with rate limiter, however, as you can see in the screenshot, the `rate` of the enqueue metrics is around 20 per second, if our rate limiter is working as expected, only 2 error modules can't generate such high number of requeue metrics, right?
![image](https://github.com/user-attachments/assets/af5aaf22-d3e0-4cfb-9b46-9ffe674a2ce8)
