### ISSUE TITLE
Fix manual E2E workflow dispatch with k8s version

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#2042]
### Description

The E2E test suite can not be run at the moment with a specific Kubernetes version set as manual workflow dispatch in Github Actions. Investigate why the pipeline is failing and fix it.
Testing with version 1.31 lead to failure.

### Acceptance Criteria

- [ ] [TestSuite E2E workflow](https://github.com/kyma-project/lifecycle-manager/actions/workflows/test-e2e.yml) can be executed manually with a given Kubernetes version

### Attachments

Example run: https://github.com/kyma-project/lifecycle-manager/actions/runs/11933648805

**Comment by c-pius** [comment]
https://github.com/kyma-project/lifecycle-manager/blob/ac820ab30dfe38a04873959dff1fdb93f9248aa4/.github/workflows/test-e2e.yml#L27C84-L27C118

uses `github.event.pull_request.head.sha` which is likely not available on manual dispatch.
