### ISSUE TITLE
[Module Catalog] Support `internal` and `beta` flags for updated module metadata

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#2059]
### Description

Current ModuleTemplates support `operator.kyma-project.io/internal`, `operator.kyma-project.io/beta`, and `operator.kyma-project.io/sync` flags (see also [docs](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/contributor/resources/03-moduletemplate.md#operatorkyma-projectio-labels)).

With our change to the split setup with ModuleTemplates and ModuleReleaseMeta, this doesn't cover the full story anymore. E.g., if a beta ModuleTemplate is synced to a beta SKR, how can it be enabled? Right now, we would need to reference it in a ModuleReleaseMeta which is synced to all clusters, not only beta ones.

The simple idea is to also introduce `beta` and `internal` flags to `ModuleReleaseMeta.spec`. Dashboard and CLI should then only display those modules depending on the presence of the same flags in the KymaCR.

In addition, we introduce `spec.internal` and `spec.beta` on the ModuleReleaseMeta level with the same behavior as for ModuleTemplate. 

### Reasons

Right now we have undefined behavior / an incomplete story for that case.

### Acceptance Criteria

- [x] Given ModuleReleaseMeta with `.spec.internal`
  - [x] only sync ModuleReleaseMeta to SKRs where KymaCR is marked with `operator.kyma-project.io/internal`
  - [x] only sync ModuleTemplates of the same module to SKRs where KymaCR is marked with `operator.kyma-project.io/internal`
- [x] Given ModuleReleaseMeta with `.spec.beta`
  - [x] only sync ModuleReleaseMeta to SKRs where KymaCR is marked with `operator.kyma-project.io/beta`
  - [x] only sync ModuleTemplates of the same module to SKRs where KymaCR is marked with `operator.kyma-project.io/beta`

**Comment by c-pius** [comment]
@mrCherry97 we are planning to move the `internal` / `beta` flags to the `.spec` of the new ModuleReleaseMeta resource. When true, the ModuleReleaseMeta and related ModuleTemplates will only be synced to those SKRs where the same is true. Does that work for you or any concerns?

**Comment by c-pius** [comment]
Yes exactly. The current behavior doesn't change. It is just that the indicator whether a module is in `beta` moves from the ModuleTemplate to the ModuleReleaseMeta.

**Comment by mrCherry97** [comment]
Okay, so it's fine for us, I made an issue to adjust this changes in Busola after your merge.

**Comment by c-pius** [comment]
Re-opening to address the additional topic of preventing installations of unsynced modules.

**Comment by mrCherry97** [comment]
Hi @c-pius, are these changes released on DEV? I reopened an issue for us to adjust the `Add Modules` view, and I'm wondering if we can pick it up in the oncoming days. Thanks in advance!

**Comment by c-pius** [comment]
Hey, no, not yet. Regular plan would be Friday. Does that work for you or do you prefer to get it earlier?

**Comment by mrCherry97** [comment]
yes, that sounds good, thanks!

**Comment by c-pius** [comment]
@mrCherry97 the change is on DEV now. In case you are playing around with beta/internal on the ModuleReleaseMeta, it takes about 5 mins to sync that to the SKR. We are working on speeding that up :)

**Comment by c-pius** [comment]
Not possible to verify on STAGE as we don't have ModuleReleaseMetas there yet. But can confirm that on DEV the sync works as expected, and when trying to enable a not synced module we get:

```
  - channel: regular                                                                 │
│     fqdn: kyma-project.io/module/template-operator                                   │
│     message: 'module template not allowed: module is beta or internal'               │
│     name: template-operator                                                          │
│     state: Error          
```
