### ISSUE TITLE
[Module Catalog] Fetch Mandatory ModuleTemplate which has the highest version

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#2068]
### Description

We agreed to have the name of the mandatory ModuleTemplates the same format as that of the regular ModuleTemplates `modulename-version`. So we need to handle the case when there are multiple ModuleTemplates for the same Mandatory Module by using the ModuleTemplate with the highest version.

### Acceptance Criteria

- [x] Add the logic to fetch the ModuleTemplate with highest version for mandatory modules.
- [x] Add an E2E test scenario with two ModuleTemplates with different versions for a mandatory module.  (Validate its installation as well as its deletion).
- [x] Add documentation that for mandatory modules, KLM will install the module template with the highest version in case there are multiple
- [ ] Follow-up on informing neighbors that modulectl can now also be used for mandatory modules

### Feature Testing

Integration tests, End-to-End tests, Unit tests

**Comment by c-pius** [comment]
Verification blocked by https://github.com/kyma-project/lifecycle-manager/issues/2177

**Comment by c-pius** [comment]
I will take care of this once I am back from vacation. Moving to blocked again for the meantime, sorry!

**Comment by c-pius** [comment]
Framefrogs are deploying a new version of kim-snatch (1.0.2) to DEV soonish. Once this is deployed, we can verify that this works properly.

**Comment by c-pius** [comment]
Seems to work. Initial state was `kim-snatch` had `regular:1.0.1`, `experimental:0.0.8` and `dev:1.0.1` MTs where `1.0.1` was the installed version according to manifests.

On 2025-04-24, they updated `dev:1.03` at `2025-04-24T08:03:10Z`. Later they also updated `regular:1.0.3` at `2025-04-24T10:14:34Z`. The manifests for `kim-snatch` show that the version has been updated at `2025-04-24T08:03:10Z`, so already with the bump of the `dev` channel. Therefore we can assume that KLM fetched the highest version of the module for installation.
