### ISSUE TITLE
Getting rid of Makefile in template operator

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#226]
**Description**

The Makefile in the template operator has to be deleted and all logic has to be migrated to the Kyma CLI commands:

* The `create module` will cover
    * Bundle the Module Operator Chart (aka. `module-operator-chart`)
    * Build the Module Image and push it to a registry defined in IMG_REGISTRY (aka `module-image`)
    * Build the Module and push it to a registry defined in MODULE_REGISTRY (aka `module-build`)

AC:
* Kyma CLI `create module` command covers the above mentioned `make` targets

**Comment by Tomasz-Smelcerz-SAP** [comment]
@tobiscr The third AC (`Build the Module and push it to a registry defined in MODULE_REGISTRY (aka module-build)`) is a bit misleading: Currently it invokes `kyma alpha module create`, and pushes nothing.
I think what is necessary there is to implement the push to the registry in the CLI after the module is succesfully built locally.

**Comment by Tomasz-Smelcerz-SAP** [comment]
The plan for the implementation.
I just followed the steps from the Makefile. The order of some steps may be changed to simplify the implementation.

```
1) Bundle the Module Operator Chart (aka. module-operator-chart)
  - invoke 'make manifests' in the operator directory (external command)
  - ensure kustomize is available (already implemented in the CLI)
  - create necessary directories
  - invoke kustomize in the operator/config/manager to `set image controller=${IMG}` (external command)
  - invoke `kustomize build` in the operator directory with the output configured to the module's `templates` directory (external command)
  - generate Chart.yaml (Go template generation, simple)

2) Build the Module Image and push it to a registry defined in IMG_REGISTRY (aka module-image)
   The `module-image` actually builds an operator image and pushes that to the docker registry
   - Invoke 'make docker-build docker-push` in the operator directory to build and push operator image to the registry (external command)

3) Build the Module and push it to a registry defined in MODULE_REGISTRY (aka module-build)
   The module building and pushing is there already. Perhaps we need to review the flags, make some of them mandatory etc.


```

**Comment by jakobmoellersap** [comment]
Notes from discussion with @clebs

1. There should be no folder structure necessary anymore, kyma alpha init module will become obsolete as we don't need additional folders anymore
2. kyma alpha create module will have 2 code paths: PROJECT discovery, and wildcard
3. For wildcard (create module from scratch) it will be based on the folder the command was executed in and the specified layers. If there are no explicit layers mentioned, everything will be put under one default layer (type has to be specified). If there are explicit layers, use them instead
4. For PROJECT, use the layout of kubebuilder (https://kubebuilder.io/reference/project-config.html) and determine the previous Makefiles Layers: Config layer (if present) in folder should come from "config.yaml", Chart Layer should be created based on the kustomization default target, that is always created in the makefile (config/default). The Default Data should come from config/samples/*, if there is more than 1 candidate it should query for an explicit candidate to define the correct default CR. For now we only support go/v3 and go/v4-alpha/v4 of kubebuilder as layouts.

=> This means for kubebuilder-based projects, there is no need to define any folder strucutre anymore

**Comment by clebs** [comment]
Hi @Tomasz-Smelcerz-SAP,
the Kyma CLI already has the feature of pushing OCI images into a registry when created (see: https://github.com/kyma-project/cli/blob/main/cmd/kyma/alpha/create/module/module.go#L132).

The `--registry` flag has to be provided for the push to happen for 2 reasons:
1. Add the registry to the component descriptor when creating it (what @tobiscr mentioned with `MODULE_REGISTRY`).
2. The CLI needs to know where the image needs to be pushed.

To get rid of the `Makefile`, we need to refactor the layering engine and the module-template generator.

**Comment by NHingerl** [comment]
Pls ping me when this is done so I can progress with https://github.com/kyma-project/community/pull/711#discussion_r992174019

**Comment by jakobmoellersap** [comment]
@NHingerl I mentioned how I think we do not need to wait there in https://github.com/kyma-project/community/pull/711#discussion_r1000410132. I think you are not blocked by this
