### ISSUE TITLE
Fix existing bugs to enable load testing

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#228]
### Description:
After e2e testing for watcher deployment on load-test gardner clusters, we discovered some bugs which may block the load testing progress: 

**Existing Bugs**:

- `skr-webook` helm chart not deployed correctly
- `skr-webook` deployed in default namespace
- `kcp.IP` and `kcp.Port`not passed as chart arguments.

```
1.6645464436851554e+09	ERROR	skr-webhook		{"error": "Post \"http://kcp.ip/v1/lifecycle-manager/event\": dial tcp: lookup kcp.ip on 100.104.0.10:53: no such host"}
github.com/kyma-project/runtime-watcher/skr/internal.(*Handler).sendRequestToKcp
```

_Originally posted by @ruanxin in https://github.com/kyma-project/lifecycle-manager/pull/224#pullrequestreview-1127014853_

**Comment by adityabhatia** [comment]
Fixed in this PR https://github.com/kyma-project/lifecycle-manager/pull/236/commits/9af547cd1aadd283e5911ef18a8dc7d657a63bae#diff-28823c7f87387cdc0cd68c606bbca94a8e4c675690d3b9c6635a052a9b58caccR14-R29
