### ISSUE TITLE
Adjust control-plane Kustomization to support watcher

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#243]
To ensure a proper a release flow, I need to ensure that deliveries can be done with kustomize easily and without problems. For this I need to integrate a kustomize enabled deployment into a Landscape and provide a guide on how to properly maintain it. One will also have to find automation capabilities:

- [ ] Have a working Kustomize Setup for a Control-Plane Deployment
- [ ] Have a small Guide setup that describes how to maintain the Control-Plane Deployment
- [ ] Propose a way to automate the setup and also multi-stage releases to dev/stage/prod

**Comment by janmedrek** [comment]
Until all the security measures are implemented we should not turn it on: https://github.com/kyma-project/lifecycle-manager/issues/144

**Comment by lindnerby** [comment]
Part I of this will be: https://github.com/kyma-project/lifecycle-manager/issues/704
