### ISSUE TITLE
Fix watcher reconciler bugs for load testing

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#245]
## Description
Currently, the watcher reconciler has bugs that are blocking the load testing task.

## ACs:

- [x] Deletion step: Virtual service is not valid when removing the last watcher CR (validation needs at least one route):
https://github.com/kyma-project/lifecycle-manager/pull/246/commits/03360465ec2ac916cf4874e26cb426c4bb4ff894
- [x] Make helm value overwrite working:
https://github.com/kyma-project/lifecycle-manager/pull/246/commits/62c046405516082888974affd3b9624c7c65cea0
- [x] Fix: failing logic and tests:
https://github.com/kyma-project/lifecycle-manager/pull/246/commits/126961ec6a447162ea357d48032c68bcd1ea4e41

**Comment by tobiscr** [comment]
Obsolete, closing it.
