### ISSUE TITLE
bug: Kyma in Ready state doesn't reflect changing Manifest states

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/lifecycle-manager#261]
**Description**
Consider a Kyma CR which is not Ready state with a module. For this module there also exists a Manifest CR. 
Now, when this module is removed the Manifest CR goes into Deleting state, but this is not reflected in the Kyma CR state, it is always Ready.

**Solution**
Ready Kyma in the above scenario should go into Processing and eventually Ready.

**Comment by jakobmoellersap** [comment]
This is fixed with https://github.com/kyma-project/lifecycle-manager/pull/264 as the informer was not started up
