### ISSUE TITLE
Ensure that we remove the watcher CRs first before uninstalling the lifecycle-manager.

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#269]
## Description:

When uninstalling the central operators, the `kcp-system` namespace is not deleted because of the watcher CRs that still have finalizers.

## ACs:

- [ ] If a namespace that has watcher CRs is being deleted. delete watcher CRs' finalizers for it to be deleted successfully.

**Comment by khlifi411** [comment]
This Bug will be fixed by removing the watcher CR finalizer after implementing the new approach described here: #266

**Comment by khlifi411** [comment]
We decided not to remove the finalizers. We still need to ensure that we remove the watcher CRs first before uninstalling the lifecycle-manager.

**Comment by janmedrek** [comment]
The Watcher CRs are included in the kustomization, and will be taken care of automatically.
