### ISSUE TITLE
Step-by-step guide for Kyma module developers

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#279]
**Description**

For a fast and repeatable ramp-up of joining Kyma module developers, a step-by-step guide is required which explains:
- how a Kyma module can be created,
- how to start implementing a custom operator, 
- how to test it locally

AC:
- [x] steps to create the Kyma module folder structure (e.g. init module etc.)
- [x] where / how to start implementing a custom operator 
- [x] bundling and testing a the Kyma module within a local test environment
- [ ] adjust the guide to point out that the unstable version of the CLI should be used
- [ ] the guide is reviewed by the Technical Writers team

**Comment by jakobmoellersap** [comment]
Reopening for Tech Writer Review and Other Refinements

**Comment by janmedrek** [comment]
Closing with the current template-operator guide rework: https://github.com/kyma-project/template-operator/pull/12
