### ISSUE TITLE
Client cache invalidation mechanism for changing secrets

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/lifecycle-manager#281]
**Description**
The remote client cache `(operator/pkg/remote/client_cache.go)` implements a client caching mechanism, which returns and saves cache entries. However, a mechanism is required to delete cache entries or invalidate them in scenarios like - deletion of Kyma CR or kubeconfig rotation stored in a secret. 

Consider including both the TTL and forced eviction on errors.

**Acceptance Criteria**

- [x] Implement invalidation (or deletion) if the remote cluster is not reachable - the kubeconfig should be removed from the cache and a new one should be fetched from the secret
- [ ] Add E2E test for that scenario

**Comment by janmedrek** [comment]
This one waits for details on the kubeconfig contract, to be clarified in this epic: https://github.com/kyma-project/lifecycle-manager/issues/12
