### ISSUE TITLE
Move Template Operator to Separate Repository instead of a subfolder in Lifecycle Manager

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/lifecycle-manager#293]
As a Module Developer I want easy access to module documentation and development guides that are easy to understand and access. The easiest way to achieve this is by moving template operator to a separate Repository. This also enables some follow-up Clean-Up for maintenance of lifecycle-manager (and also module-manager)

AC:

- [x] Move Template Operator from https://github.com/kyma-project/lifecycle-manager/tree/main/samples/template-operator to a separate repository.
- [x] Decide naming on template operator (e.g. sample-operator / template-manager / template-operator, etc...)
- [x] Correct all links in documentation in template operator and community guides to link to the new repository instead
- [x] Move Lifecycle Manager Operator part with go.mod to Root after the move has been completed to clean up the Lifecycle Manager Repo after the Move
- [x] create template operator pipelines once the move has been completed

**Comment by jakobmoellersap** [comment]
Adjustmen of Lifecycle Manager Repo in https://github.com/kyma-project/lifecycle-manager/pull/300

**Comment by jakobmoellersap** [comment]
Regular jobs will fail as it also changes the destination of the jobs (now being in root) so one has to also adjust the pipelines: https://github.com/kyma-project/test-infra/pull/6342

New Template-Operator will be located in https://github.com/kyma-project/template-operator/pull/1

**Comment by jeremyharisch** [comment]
Reopening since the Pipelines are not implemented
(Issue got closed by kyma-bot)

**Comment by jeremyharisch** [comment]
PR to introduce the template-operator pipelines
https://github.com/kyma-project/test-infra/pull/6382

**Comment by jakobmoellersap** [comment]
@jeremyharisch i think we need to reopen, your linked PR closed this issue.
