### ISSUE TITLE
Align the logging format for Lifecycle + Module Managers with the Consistent Logging Concept

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/lifecycle-manager#299]
Implement based on kyma community concept - Consistent Logging
https://github.com/kyma-project/community/tree/main/concepts/observability-consistent-logging

ACs:

- [x] lifecycle manager is adopted to standardized logging format
- [x] module manager is adopted to standardized logging format

**Comment by ruanxin** [comment]
included in the following two PR
https://github.com/kyma-project/module-manager/pull/167/files#diff-f7893cd19dbd21bb6025ab8336c0fa1799f30e7cfcd17fd0cbcb73c7c0d1e3b9R112-L114

https://github.com/kyma-project/lifecycle-manager/pull/295
