### ISSUE TITLE
Refactor SKR watcher installation to use native Kubernetes client

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#301]
**Description**
Using the native Kubernetes client to install the SKR watcher should be implemented and relying on the manifest library should be removed.

**ACs**

- [x] Remove dependency between SKR chart installation and the manifest library and use native Kubernetes client instead.
- [x] Use trigger label with `secretResourceVersion` value to ensure pods restart when chart is redeployed.
- [x] Use sync context on Kyma reconciler setup and pass it to `ChartManager` method calls as needed
- [x] The SKR web-hook's installation should leverage SSA to be idempotent.

And ensure that:
- [x] the `caBundle` configured for each deployed `webhook` configuration is the same as the `ca.crt` field of the `tls-secret`

**Related discussions**

https://github.com/kyma-project/lifecycle-manager/pull/277#discussion_r1014820030
https://github.com/kyma-project/lifecycle-manager/pull/277#discussion_r1014819992
https://github.com/kyma-project/lifecycle-manager/pull/277#discussion_r1011751082

**PR**
#313

**Comment by jakobmoellersap** [comment]
Please fill TBD fields @khlifi411
