### ISSUE TITLE
Implement Watcher CR state handling

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#302]
**Description**
We are missing a state on Watcher CR if the Virtual Service has been created/updated correctly. 

**Reasons**
Central (in-KCP) Module developers would like to know what is the state of the resources managed by the Watcher Reconciler.

**ACs**
- [x] Propose a solution regarding the State object, we can do something similar to the one in Kyma CR
- [x] Implement state handling for watcher CRs in the watcher reconciler
- [x] Implement tests for state handling

**Related discussions**
https://github.com/kyma-project/lifecycle-manager/pull/277#discussion_r1014820500

**Comment by jakobmoellersap** [comment]
Please add ACs @khlifi411
