### ISSUE TITLE
Enable watcher implementation to be tested in the dual-cluster local setup

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#303]
**Description**
This implementation is too opinionated on load balancer only. I think we should at least offer node-port to allow implementation tests in the setup with two different clusters.

**ACs**
- [ ] leverage k3d's `host.k3d.internal` hostname to establish watcher communication between local k3d clusters.
- [ ] write a step-by-step user-guide for testing watcher on local cluster

**related discussions**
https://github.com/kyma-project/lifecycle-manager/pull/277#discussion_r1014072116

**Comment by jakobmoellersap** [comment]
Please add ACs @khlifi411
