### ISSUE TITLE
Provide a way to stop reconciliation for Kyma clusters

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#315]
**Description:**
We need a way to exclude specific clusters from the reconciliation process completely. This is sometimes helpful for developing or troubleshooting particular Modules - developers will be able to introduce local changes to their configuration, allowing them to test unreleased functionalities or introduce some experimental configuration changes.

**Acceptance Criteria:**
- [x] Propose solution and consult with the development teams
- [ ] Specific clusters can be excluded from the time-based reconciliation
- [ ] With "noop" enabled the whole reconciliation is blocked, this applies to:
  - Synchronizing Kyma CR
  - Installing/removing Modules from the cluster
  - Updating/reverting charts for the Module Operators

**Comment by jakobmoellersap** [comment]
I suggest to use a label according to a preexisting solution in module manager: https://github.com/kyma-project/module-manager/blob/2f825c4c51e5c1329021ecf83daa138202af50ac/pkg/declarative/v2/options.go#L299-L303

This uses `declarative.kyma-project.io/skip-reconciliation`. I suggest to introduce a manifest specific version called `operator.kyma-project.io/skip-reconciliation` that is overriding the default and is also usable within lifecycle-manager to skip kyma reconciliation.

**Comment by jakobmoellersap** [comment]
Solution provided by https://github.com/kyma-project/lifecycle-manager/commit/304edc65d6b38834ca4375983ad5d80cb26a6677
