### ISSUE TITLE
Verify kyma.Spec.Sync combination

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#320]
We use kyma CR Spec.Sync fields to control the behavior how kyma CR synced to remote. However not all combination of the attributes are valid.  

Implement following logic into validating admission webhook:
If `kyma.Spec.Sync.Enabled` set to `false`, `kyma.Spec.Sync.ModuleCatalog` can't be `true`

# Dev Notes
Also check current implementation if the usage of `Sync.ModuleCatalog` has conflict with `Sync.Enabled`

**Comment by janmedrek** [comment]
Blocked by: https://github.com/kyma-project/lifecycle-manager/issues/392
