### ISSUE TITLE
Istio-Overrides: KCP Gateway Setup

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#325]
**Description:**
In the KCP setup the lifecycle-manager will have its own Istio Gateway to receive incoming request from the SKRs. This Gateway will have configured ports only dedicated for the Watcher request, but still using the default Istio Loadbalancer. Thus, we need to have overrides on the control-plane for the lifecycle-manger Gateway ports.

Ports are configured here: https://github.com/kyma-project/lifecycle-manager/pull/321/files#diff-f295534707b430f60b6759e2b9ebbfdf41a8a0230a18fac494ac6813fb0a934dR19-R27

ACs:
- [ ] control-plane override for default Istio LoadBalancer
  - [ ] Cover port 8080
  - [ ] Cover port 8433

**Comment by janmedrek** [comment]
The HTTPS port should be the default one, and the HTTP port should be disabled out-of-the-box.
