### ISSUE TITLE
Dynamically fetch VirtualService Hosts from Gateway

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#326]
Implementing this issue should be done after the following PR has been merged: https://github.com/kyma-project/lifecycle-manager/pull/319

**Description**
During the Watcher reconcile loop the corresponding `Istio.VirtualServices` will be created and configured. The configuration of the VirtualServices are part of the spec of the WatcherCRs, besides the `VirtualsService.Hosts`. The Hosts should be automatically fetched from the corresponding Istio. Gateway instead of a [hardcoded value](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/istio/client.go#L81).

**ACs:**
- [x] Remove hardcoded `vsHost` value
- [x] Fetch Hosts list from corresponding Istio.Gateway
- [x] Include fetched hosts into the VirtualService configuration
- [x] Determine whether the current approach is sufficient (change to the Gateway won't trigger reconciliation) if not, a follow-up or a fix should be created
- [x] Have a dedicated success interval for the Watcher
- [x] For each Watcher,  create a dedicated virtual service, it will be implemented not here, but in the following issue: https://github.com/kyma-project/lifecycle-manager/issues/336

**Comment by ruanxin** [comment]
Where is this hardcoded value come from, can you provide a bit more information here? @jeremyharisch 
```
vsHost                     = "listener.kyma.cloud.sap" 
```

**Comment by ruanxin** [comment]
management-plane-config PR: https://github.tools.sap/kyma/management-plane-config/pull/2678

**Comment by jakobmoellersap** [comment]
I believe with the latest changes we have everything in place and I do not think we need additional follow-up, thus closing
