### ISSUE TITLE
Module templates are being added and deleted on target cluster

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/lifecycle-manager#328]
Step to reproduce:

1. Create a Fresh Cluster
2. Enroll Cluster to gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev ( I'm using busola-k-test )
3. Wait for Reconciler to install Kyma specific CRDs
4. Notice the Module Templates in `kyma-system` are being added and then deleted on a interval of 5-10s 

![image](https://user-images.githubusercontent.com/478866/204292690-947a5993-f341-4e16-83d0-79c965471f51.png)

**Comment by valentinvieriu** [comment]
This bug is not fixed. The ModuleTemplates are being added an removed

**Comment by janmedrek** [comment]
Hey @valentinvieriu, can you confirm whether the issue is still present? We've introduced flexible channel names that should solve the problem of `stable` not being in the allowed values list. I hope it's already gone. 🙂
