### ISSUE TITLE
Enable users to provide non-default configuration for modules

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#344]
**Description**
When a new module is enabled in Kyma the default configuration is always applied. This means that to introduce any change, the module needs to be installed, modified, and reconciled again, which may bring unnecessary resource usage and waste time.

The solution would be to enable a way that allows providing the configuration up-front and having the module installed with the desired parameters right away.

A potential solution is to mark the module as user-configured; this way only the CRD will be installed but no CR will be created, it will be delivered by the user instead.

**Reasons**
We want to limit unnecessary operations and have a convenient way of deploying properly-configured modules at once.

**Acceptance Criteria**
- [x] Module can be marked to have deployment not include the CR (CRD only)
- [x] User-provided configuration should be picked up and accounted for during the module operator installation.

**Comment by jakobmoellersap** [comment]
Prerequisite PR for Module Manager: https://github.com/kyma-project/module-manager/pull/215
