### ISSUE TITLE
Automated performance test for the new architecture

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#359]
**Description**
We need a pipeline that will check the performance of the Modularization setup that can be run with a single trigger.

**Reasoning**
We would like to make sure we deliver a performant solution to our users.

**Acceptance Criteria**
- [ ] Consider keeping the performance cluster or running it from scratch (longer setup)
- [ ] Consider reducing the load test to 1000 clusters (more prod-oriented approach)
- [ ] Improve the resiliency of the Load Test scenario (consider switching to the native Go test)
- [ ] Pipeline for the Load Test scenario set up
- [ ] Find out the possibility of having the manual trigger - we should avoid running that automatically and only make the test after big change/refactoring was introduced
- [ ] Deploy the base Grafana set up in the KCP cluster and set up the metrics collector

**Comment by jakobmoellersap** [comment]
I suggest to prioritise this down since we currently do not need the automation as much as other stabilisation aspects.

**Comment by janmedrek** [comment]
Duplicate of: https://github.com/kyma-project/lifecycle-manager/issues/1048
