### ISSUE TITLE
Create Alert Rules for Managers in KCP

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#382]
**Description:**
In order to provide a proper operational readiness for the new Reconciler Ecosystem proper alerting needs to be set up in addition to the monitoring we have.

Alert rules with proper thresholds should be set up for all of the vital metrics exposed by our components.

**Acceptance Criteria:**
- [x] Define alerting thresholds for various metrics exposed by the Lifecycle Manager and Module Manager
- [x] Alert rules set up for:
  - Performance issues of Managers
  - Kyma CRs in Error state
  - Kyma CRs in Error state for too long

**Comment by janmedrek** [comment]
Blocked by:
https://github.com/kyma-project/lifecycle-manager/issues/380
https://github.com/kyma-project/lifecycle-manager/issues/381

**Comment by ebensom** [comment]
Alerting on Kyma and module state stuck are implemented by SRE and can be tracked here:
https://github.tools.sap/kyma/backlog/issues/3911

**Comment by lindnerby** [comment]
PR for Alert rules: https://github.tools.sap/kyma/management-plane-config/pull/3380
