### ISSUE TITLE
Introduce Kyma validation webhook

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#392]
**Description**

Currently lifecycle-manager does not have a webhook to validate Kyma CRs. We want to make sure that applies and updates where modules listed in the spec are rejected if no matching ModuleTemplate can be found.

There is a basic by-default webhook created, it acts as scaffolding and should be extended with some logic.

**Acceptance Criteria:**
- [ ] Edit a validation webhook for Kymas
- [ ] The webhook rejects a new Kyma if there doesn't exist a ModuleTemplate for a Module in `spec.modules`
- [ ] Specify events to look for
- [ ] Should be possible to deactivate the webhook in the KCP, but keep it in the SKRs (update + create)
- [ ] Validates if the module is outdated  ?
- [ ] Returns an error stating the module that was causing it ?

**Comment by janmedrek** [comment]
This could potentially introduce a big impact on the performance of the whole solution, perhaps we should reconsider implementing that.

**Comment by janmedrek** [comment]
Waiting for the https://github.com/kyma-project/lifecycle-manager/issues/320 to see if there are no performance consequences.
