### ISSUE TITLE
Bug: Kyma CR gets deleted before Manifest CRs

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#431]
**Description:**
To each Kyma CR reside one or multiple Manifest CRs, depending on how many modules are in the spec of the Kyma CR mentioned. If a Kyma CR gets deleted all corresponding CRs should be deleted as well, this includes also Manifest CRs.

Currently, it can happen that the Kyma CR gets deleted before all corresponding Manifest CRs are deleted. Thus, the Manifest will be orphaned and will end in an infinite loop of switching from `Deleting` state to `Error`. Thus, it needs to be deleted by hand, by removing it and its finalizers manually.

**Steps to reproduce:**
1. Deploy KLM locally on a k3d cluster, create KymaCR and correpsonding secret; You can use local setup guide: https://github.com/kyma-project/lifecycle-manager/blob/d94177b34bf404ad77f2d905689b59b5a98fa6e9/docs/developer/local-test-setup.md
2. Delete Kyma CR
3. Check if Manifest CR got deleted

**ACs:**
- [ ] Before all finalizers are removed from Kyma CR, it needs to be sure that all corresponding Manifest CRs have been removed

**Comment by jeremyharisch** [comment]
The described behaviour is actually wanted behaviour, which was in longer discussion.

The reason why it is wanted behaviour is, that we rely on the garbage collection of Kubernetes.  If we delete a KymaCR using `kubectl` by default the [background cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#background-deletion) will be used. This means, it will trigger the deletion of all resources which have an ownerReference to this KymaCR - then then KymaCR will be deleted, without waiting for the other resources to be deleted fully.

To actually wait for the other resources to be deleted the cascade flag of the delete command needs to be used correspondingly, like the following
```
kubectl delete kyma kyma-sample -n kcp-system --cascade="foreground"
```
Then the [foreground cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion) will be used and the KymaCR will get a finalizer, called `foregroundDeletion` and this finalizer will be removed by the kubernetes API if all resources with an OwnerReference to this KymaCR are fully deleted.

We could also implement this mechanism on our own, but this would mean we are implementing our own garbage collection, which is additional work to do and maintain, plus this is reinventing the same solution to the same problem.

I will leave some room open for discussion before closing that issue

**Comment by ruanxin** [comment]
First I think we should not call it wanted behavior, it's expected, but not what we want, the behavior still should be Kyma CR get deleted only after all modules get deleted. It's just we currently rely on the k8s-supported foreground deletion for this purpose but do not implement our own solution.

As discussed, we should also align with KEP team about this decision to use foreground deletion to prevent kyma CR to be deleted without knowing the status of manifest CR, and they should be aware that default deletion does not maintain the cascading relations between Kyma CR and manifest CR.

**Comment by jeremyharisch** [comment]
Since we agreed on using foreground deletion by default, we can close this issue
