### ISSUE TITLE
Threat modelling for new reconciler architecture

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#44]
The new reconciler architecture has to pass a threat modelling workshop as part of the SAP product standards. The threat modelling workshop has to be planned and executed together with security experts and findings have to be solved before the Go-Live happens.

AC:
* Plan and execute threat modelling workshop with security experts
* Track findings in dedicated issue tickets and mark go-live relevant issues accordingly

**Comment by jakobmoellersap** [comment]
Waiting for Thread Modelling Output to then translate into MVP Tickets

**Comment by tobiscr** [comment]
Sec-workshop finished, further tickets created for implementing the different mitigation strategies: https://github.com/kyma-project/lifecycle-manager/issues/144
