### ISSUE TITLE
Limited modules availability per Kyma instance

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/lifecycle-manager#455]
**Description:**
Provide a way to limit the list modules available for the Kyma instance. It can be a label or annotation on the Kyma instance created in the control plane. The expected behaviour is that only module templates that match the Kyma resource label can be copied to the SKR and used to install modules.

In other words, there are groups of users in the same landscapes (dev-stage-prod) that should have different modules available to them. It is important to provide a mechanism that will be able to determine module templates should be synced to which SKRs.

Example:
- Kyma runtime A, used by an external customer, should not have an access to modules marked as internal
- Kyma runtime B, used for internal development, should have an access to internal modules

**Reasoning**
We need to support internal modules that should not be shared with other users. Those modules should be available to certain groups of clusters.

**Comment by janmedrek** [comment]
## Label-based approach
- Labels should exist only in the KCP cluster, those should not be propagated to/from the SKR
  - channel name validation rules: https://github.com/kyma-project/cli/blob/e80945d151f95a7f76baf4ade4ca437cd6ce05d1/cmd/kyma/alpha/create/module/opts.go#L83
- Label set up per channel for every Kyma resource
- Label has two values: `enabled` and `disabled` indicating whether a corresponding channel should or should not be synced
- If there is no label channel present for a given Kyma CR then the channel does not get synced

- Determine the behaviour for removing the modules in channels that were previously synced but should no longer be present. Related: https://github.com/kyma-project/lifecycle-manager/issues/457

Migration steps:
1. KEB should add channel labels when the Kyma CR is created
2. Migration script (label all the Kyma CRs) prepared and ran
3. KLM version bumped

Later on, we could consider moving that from labels to spec (as a part of a new version of API being released).

**Comment by LeelaChacha** [comment]
After a talk with @janmedrek, we decided that the desync behaviour of later-disabled channels shall be implemented later.

**Comment by janmedrek** [comment]
As we've talked with @pbochynski we may need an extended solution for limiting the availability of the ModuleTemplates which is not based on channels.

When we have the concept ready we can start the work again on this task.

**Comment by pbochynski** [comment]
I created a proposal here: https://github.com/kyma-project/community/issues/770

**Comment by janmedrek** [comment]
Implementation suggestions: https://github.com/kyma-project/lifecycle-manager/issues/542#issuecomment-1517370383
