### ISSUE TITLE
Security Considerations: Module Signature Configuration Enforcement through Signature Validation

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/lifecycle-manager#456]
As a module user, I want to make sure I have the required provenance available to verify that all modules I want to install in my cluster can be trusted and are integral and not mutated. Thus I want to be able to verify the module data through an inbuilt mechanism.

For this to work, the existing module descriptor in the ModuleTemplate is an issue. Since the descriptor is accepted as [runtime.RawExtension](https://github.com/kyma-project/lifecycle-manager/blob/main/api/v1beta1/moduletemplate_types.go#L99) into the API-Server, we currently cannot avoid changing the data of the ModuleTemplate descriptor after it was accepted into the API-Server.

The only way to discover this tampering is by enforcing change denial in the admission webhook that already validates the ModuleTemplate.

For this to work we have to make use of the inbuilt signature support for ModuleTemplates.

Let's imagine a ModuleTemplate is signed by the key`private.pem` and can be verified with `public.pem`. (To sign a module, we can use `kyma alpha sign module` and to verify `kyma alpha verify module`, but there is no way to create a `template.yaml` with the signature included in CLI yet). Let us also assume that the key-pair above was created from an intermediary certificate that is trusted.

Now we need to assure the following for the `ModuleTemplate`:
1. Every time a change is made to the `ModuleTemplate` without a signature, we need to deny the request (as the signature always needs to be `enforced` or otherwise it could be skipped), this can also be termed `strict` validation
2. Every time a change is made to the `ModuleTemplate` with a signature, we need to verify the signature with a public-key that is either
  - inbuilt into the binary (e.g. for all kyma-modules we have an inbuilt public key)
  - accessible as a trusted secret in the cluster (e.g. for third-party signatures or modules)
3. When the Signature is accepted, only then the Update of the AdmissionWebhook will be accepted as well.
4. In case of denial, we will deny the request to change the ModuleTemplate.

Now that we setup the ModuleTemplate for verification, the next step is to safeguard the `Manifest` from changes. here we have a few Options:

1. The easy way: Rely on Lifecycle Manager to reconcile out bad changes inconsistent with the ModuleTemplate but accept side-effects between the discovered change and the correction.
2. The hard way: Refactor the Manifest API to only hold a reference to the descriptor instead of copying layer data. This way we can assure provenance by relying simply on being able to only reference module-templates that use already verified `ModuleTemplates`. Then the descriptor can be verified in the manifest just like in the ModuleTemplate.

The result of this should:
- [ ] ensure that we can enforce signature validation and reject updates and ModuleTemplates with non-verified
- [ ] ensure that the CLI `kyma alpha create module` can create templates with descriptors that are already signed instead of having to use `kyma alpha sign module` and then copying out the descriptor again.
- [ ] Ensure that the lifecycle manager contains a preset signature that is used by default to verify modules from the `kyma-project.io` domain

**Comment by ruanxin** [comment]
@TorstenD-SAP , regarding the private key format, do we have a specific requirement here, our current implementation only support RSA key in `PKCS #1` format, is it acceptable? do we need to support `PKCS #8` as an additional or even have more strict recommendation here?

**Comment by ruanxin** [comment]
I guess it's clear now based on the current ocm spec,`Currently only signing according [RSA PKCS #1 v1.5 signature algorithm](https://datatracker.ietf.org/doc/html/rfc3447) supported.`  https://ocm.software/docs/guides/getting-started-with-ocm/#sign-component-versions

**Comment by janmedrek** [comment]
To consider:
- rotation of certificates used for signing/verification
- revoke list

**Comment by ruanxin** [comment]
This issue is not relevant anymore, atm, the Module submission is fully controlled by us (neighbour team), the validation of Module should be done in submission pipeline, LM only consume verified module template in KCP, there is no needs to do Module validation through signature.
