### ISSUE TITLE
`Declarative Reconciliation Library Reference Documentation` link is broken.

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/lifecycle-manager#472]
in [reference-documentation.md](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer/reference-documentation.md) the link to [Declarative Reconciliation Library Reference Documentation](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/declarative/README.md) is broken. Please fix or remove the link.

**Comment by janmedrek** [comment]
Fixed in https://github.com/kyma-project/lifecycle-manager/commit/a009012557c6735ff3461d13ee606eba06c3e0e0
