### ISSUE TITLE
remove leader election option for Lifecycle Manager

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#476]
The kubebuilder default scaffold providing LeaderElection option as a feature flag which by default disabled. 

However for our Lifecycle Manager project, we need to ensure that LeaderElection is always enabled. This is because our controller logic requires a single leader instance to manage the lifecycle of the resources and prevent conflicts or inconsistencies. Therefore, we need to modify the configuration yaml files to remove the `--leader-elect` flag and hardcode the LeaderElection option to true. This way, we can avoid potential side effects or errors caused by user misconfiguration or multiple leader instances.

AC:
- [x] `LeaderElection` should by default enabled in Lifecycle Manager and not be configurable
- [x] `--leader-elect` args should cleanup in config yaml

**Comment by amritanshusikdar** [comment]
Upon starting with the issue the following problems were encountered:
1. Changed the leader election flag to true &rarr; led to name space error
2. Added namespace option and hardcoded it to `kcp-system` &rarr; the operator complains about namespace not found
        ➡ This is because of a potential race condition because during the initialisation of the LifecycleManager the `kcp-system` namespace does eventually get created, but only after the leader election takes place. Hence it never finds it in the first place.
3.  Adding the code/command for the manual creation of this namespace &rarr; more problems as it is an anti-pattern and caused more cleanup issues.

After a detailed discussion with @ruanxin we came to the conclusion that this issue can be closed, as implementing it brings more overhead than benefits.
