### ISSUE TITLE
Make sure lifecycle-Manager image version consistent with kustomize deploy

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#487]
**Issue:** 
The current deployment of Lifecycle-Manager in KCP using Kustomize does not ensure versioning consistency for Lifecycle Manager deployment.

**Background:**

- The current deployment of Lifecycle-Manager in KCP uses a fixed ref in management plane config
- The image tag used for Lifecycle Manager instance is always `latest`, which can cause problems if the latest image is not compatible with the current configuration or environment. See [image tag](https://github.com/kyma-project/lifecycle-manager/blob/main/config/manager/kustomization.yaml#L19).

**AC:**
- [x] Updating the image tag with the current tag after each PR gets merged, to ensure that the deployed Lifecycle Manager instance matches the source code and configuration of that PR.

**Comment by LeelaChacha** [comment]
The PR is on the [management-plane-config repo](https://github.tools.sap/kyma/management-plane-config/pull/3199)
