### ISSUE TITLE
Remove flaky deprecated condition test

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#508]
The current [Kyma with deprecated Condition](https://github.com/kyma-project/lifecycle-manager/blob/main/controllers/kyma_controller_test.go#L33-L54) is quite unreliable. the main reason is, the status.condition is the subresource, and our lifecycle-manager reconcile update the kyma status very frequently, the patch in the test will often face race condition while writing the condition. Instead of writing this integration test, we can just unit test that function which removes deprecated conditions. Follow up issue to refactor the init logic: https://github.com/kyma-project/lifecycle-manager/issues/509

AC:
- [x] kyma with deprecated condition test removed

**Comment by amritanshusikdar** [comment]
Since the change requested in this issue is quite small, it is being handled in the followup issue #509.

Closing this issue.
