### ISSUE TITLE
Disable unnecessary default metrics

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#511]
by default, controller-runtime internally defined some performance related metrics. However, some of these metrics are not very useful for our purposes and they consume a lot of resources from the prometheus server.

The metrics should be ignored:
`rest_client_request_duration_seconds_bucket`
`rest_client_request_size_bytes_bucket`

However, it might be not possible to disable them on the client application, since controller-runtime hardcoded the registry in the init() function internally.

Therefore, we need to find a way to ignore these metrics on the prometheus server side. One possible solution is to use a relabel config in the prometheus configuration file. A relabel config allows us to modify or drop labels before they are stored or scraped by prometheus.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

AC:
- [ ] stop KCP promethues server scraping those metrics mentioned above

**Comment by lindnerby** [comment]
Reprioritising this to 3: we can have a look at client-side metric reduction at some point, but it is not urgent. Cardinality is not a problem and SRE is handling scrape configs for KCP.
