### ISSUE TITLE
Redesign lifecycle_manager_kyma_status metrics

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#513]
One of the challenges of monitoring and alerting systems is to deal with high cardinality of metrics, which means having a large number of possible combinations of labels and values for each metric. High cardinality can lead to performance issues, increased storage costs, and reduced query efficiency. Therefore, the amount of labels should be carefully considered when designing metrics.

At the moment, for this `lifecycle_manager_kyma_status` metric, we have 4 labels:
```
prometheus.Labels{
	kymaNameLabel:   kymaName,
	stateLabel:      string(newState),
	shootLabel:      shoot,
	instanceIDLabel: instanceID,
})
```
 Assuming that there are N Kyma instances on N SKR clusters, and that each instance can have one of three possible states (ready, processing, or error), the total number of time series identifiers generated by this metric will be N^3 * 3.

It may not be necessary to have three labels that represent the same thing: the SKR cluster. In fact, normally the shoot, kyma, and instance should represent the same SKR cluster, so we don't need to distinguish them by different labels.

AC
- [ ] Clarify the meaning of those labels with SRE, find a solution if we can reduce to only one label representing all instances.
- [ ] Redesign the  `lifecycle_manager_kyma_status` metric to reflect the new decision.
- [ ] Create or adjust the existing Grafana dashboard panel for this metric.

**Comment by lindnerby** [comment]
Since there will be 1:1 relationships between shoot, instanceID and kyma name the cardinality will not be high. There will be four unique metrics for each Kyma due to state labels. Verified with SRE and closing this.
