### ISSUE TITLE
Remove CPU limit for lifecycle manager

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#518]
Referenced article: [CPU limits on Kubernetes are an antipattern](https://home.robusta.dev/blog/stop-using-cpu-limits)

Main takeaway from this article, it's not a best practice to setup CPU limit, because it will potentially introduce CPU throttling if application has burst during high CPU usage.

AC:
- [x] lifecycle manager deployment should not set CPU limit
- [x] consult SRE regarding this change

**Comment by amritanshusikdar** [comment]
The SKR Webhook CPU Limits are preserved, aka, not removed.

**Comment by ruanxin** [comment]
let's postpone this until we resolve current high CPU usage issue:  https://github.com/kyma-project/lifecycle-manager/pull/651

**Comment by ruanxin** [comment]
done https://github.com/kyma-project/lifecycle-manager/pull/732
