### ISSUE TITLE
Migrate images to the new Artifact Registry

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#523]
**Description:**

The `eu.gcr.io/kyma-project` will soon be put into read-only mode, we need to migrate the images to the `http://europe-docker.pkg.dev/kyma-project/prod`

**Acceptance Criteria:**
- Images migrated:
  - [x] [Lifecycle Manager](https://github.com/kyma-project/lifecycle-manager/blob/main/config/manager/kustomization.yaml#L18)
  - [x] [Template Operator](https://github.com/kyma-project/template-operator/blob/main/config/manager/kustomization.yaml#L15)
  - [x] Old [Reconciler](https://github.com/kyma-project/control-plane/pull/2630/files)
  - [x] Reconciler image bump job adjusted
- [x] All the build pipelines adjusted

**Comment by lindnerby** [comment]
Also https://github.tools.sap/kyma/management-plane-config/pull/3352
