### ISSUE TITLE
Remove the `last-sync` annotation from resources

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#526]
**Description:**
Right now Lifecycle Manager applies the `last-sync` annotation to multiple resources it manages, it can create an unnecessarily high amount of K8S events for other operators that watch those resources (i.e audit logging).

There is already the last operation time in Kyma CR, those annotations are unnecessary.

**Acceptance Criteria:**
- `last-sync` annotation is no longer applied
- no migration is required in the KLM, we can go with a simple script to drop that annotation for all the resources in the cluster

**Comment by nesmabadr** [comment]
The `last-sync` annotation is added only for the remote cluster resources not for the control-plane cluster, so I don't think we need to write this script. This will require to get all the remote clusters kubeconfigs and access them to be able to drop these annotations.
