### ISSUE TITLE
Provide a way to stop ModuleTemplate synchronization to the SKRs

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#542]
**Description**

Provide a way to stop specific ModuleTemplate synchronisation to the SKR clusters.

**Reasons**

Currently, there is no way to prevent a single ModuleTemplate from being synced to the SKR clusters. It would be useful to have a possibility to disable the sync for a specific module, i.e. during the migration process. Right now the only option to achieve similar result is to turn off Module Catalog sync, which affects other ModuleTemplates as well.

**Acceptance Criteria**
- [ ] Create a way to stop single ModuleTemplate synchronisation to the SKR clusters
- [ ] The marked ModuleTemplates should not be put into the SKR clusters
- [ ] The logic could be based on a label, there is already a similar [`skip-reconciliation` label](https://github.com/kyma-project/lifecycle-manager/tree/main/api#label-based-side-effects-from-operatorkyma-projectio) for Kyma CR
- [ ] Provide a documentation of the feature

**Attachments**

N/A

**Comment by pbochynski** [comment]
If you base the implementation of https://github.com/kyma-project/lifecycle-manager/issues/455 on labels we can use it to fulfil this requirement. I can imagine that both Kyma and ModuleTemplate resources in the control plane can have labels such:
- operator.kyma-project.io/sync=true|false
- operator.kyma-project.io/internal=true|false
- operator.kyma-project.io/beta=true|false

Scenarions:
- Default: Kyma and ModuleTemplate have label operator.kyma-project.io/sync=true
- Disable module synchronisation in one cluster: remove label operator.kyma-project.io/sync from Kyma resource
- Disable synchronisation of single module: remove label operator.kyma-project.io/sync from ModuleTemplate resource
- Enable internal modules for cluster: add label operator.kyma-project.io/internal on Kyma
- Enable internal module for external customer (publish): remove label operator.kyma-project.io/internal from ModuleTemplate
- Disable synchronisation of beta modules in cluster: add label perator.kyma-project.io/beta=false on Kyma resource

**Comment by Tomasz-Smelcerz-SAP** [comment]
A quick summary of the provided AC:

scenario name: |   | Disable sync | default | disable single module | publish beta modules | publish internal modules
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |  
labels on the Kyma instance: |   |   |   |   |   |  
  | sync: | FALSE | TRUE | TRUE | TRUE | TRUE
  | internal: | - | FALSE | FALSE | FALSE | TRUE
  | beta: | - | FALSE | FALSE | TRUE | FALSE
labels on the ModuleTemplate instance: |   |   |   |   |   |  
  | sync: | - | TRUE | FALSE | TRUE | TRUE
  | internal: | - | FALSE | FALSE | - | TRUE
  | beta: | - | FALSE | FALSE | TRUE | -
  |   |   |   |   |   |  
ModuleTemplate sync is enabled (all modules) |   | FALSE | TRUE | TRUE | TRUE | TRUE
The ModuleTemplate is synced |   | FALSE | TRUE | FALSE | TRUE | TRUE

**Comment by a-thaler** [comment]
Does it mean that I as a module provider must place the "sync: true" label on the template, otherwise it will not be effective for remote clusters? I would expect that it is enabled by default and I explicitly can disable it.

**Comment by Tomasz-Smelcerz-SAP** [comment]
> Does it mean that I as a module provider must place the "sync: true" label on the template, otherwise it will not be effective for remote clusters? I would expect that it is enabled by default and I explicitly can disable it.

@a-thaler I've updated the scenario matrix with the `default` case just about the time you posted your question. My understanding of the AC's is that without any labels the sync is **enabled**. But I need to double-check on that with @janmedrek .

**Comment by valentinvieriu** [comment]
Can you confirm what is the label we will expect to detect Beta?
Is it `operator.kyma-project.io/beta=true|false` ?

**Comment by janmedrek** [comment]
@valentinvieriu the label in the linked PR is as follows:
```
BetaLabel = OperatorPrefix + Separator + "beta"
```

Which translates to:
```
operator.kyma-project.io/beta
```

And then the value is either `true` or `false`.
