### ISSUE TITLE
Remove config layer

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#543]
Since now we only support raw manifest rendering, the config layer which was previously provided as helm chart, kustomize overwrite becomes useless. We should remove any config.yaml related code in lifecycle manager.

AC:
- [x] CLI don't need to handle `config.yaml`, and generated module template should not contains config layer.
- [x] Drop the code from the CLI related to the config layer
- [x] For module template which contains config, the config layer will not rendered into manifest CR.
- [x] All code in lifecycle manager related handling this config should be removed
- [x] Update the description in the ModuleTemplate CRD to indicate that the config field is no longer used

**Be aware, eventually, manifest spec should not contain this config field, but this might introduce breaking changes, should plan it in next API version. In this issue, don't remove this Config field.** 
```
type ManifestSpec struct {
	// Config specifies OCI image configuration for Manifest
	Config ImageSpec `json:"config,omitempty"`

```

**Comment by janmedrek** [comment]
The CLI part is already done with the new way of building the Modules (based on the config file and not the kubebuilder repo).

**Comment by LeelaChacha** [comment]
One PR is still left
