### ISSUE TITLE
Clean up v1beta1

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#567]
After successfully migrated to v1beta2, we need to drop v1beta1

Steps:
- [x] #1134 
- [x] #1118
- [x] #1119
- [x] #1120 

Reference:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

**Comment by lindnerby** [comment]
⚠️ We need to consider the CRD version migration guide as described [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/).

Especially the part about [upgrading existing objects to a new stored version](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version) to prevent errors were a version has already been removed from the resource definition but objects are still stored under that version in etcd.

We will opt for using the [migrator tool](https://github.com/kubernetes-sigs/kube-storage-version-migrator) mentioned there.
