### ISSUE TITLE
Drop `runtime.Scheme` conversion

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#604]
Kubebuilder is based on controller-runtime to provide conversion webhook implementation based on [hub and spokes pattern](https://book.kubebuilder.io/multiversion-tutorial/conversion.html), which is a simplified version based on top of `k8s.io/apimachinery/pkg/runtime/scheme` conversion.

Reference: 
1. https://github.com/emissary-ingress/emissary/wiki/design-doc:-Emissary%27s-CRD-conversion-logic#how-does-that-controller-runtime-stuff-work
2. cert-manager to check how conversation webhook server created based on runtime.scheme https://github.com/cert-manager/cert-manager/blob/master/cmd/webhook/main.go

AC:
- [ ] remove unnecessary AddConversionFunc and SetVersionPriority in https://github.com/kyma-project/lifecycle-manager/blob/main/api/scheme.go#L22-L70
- [ ] prepare the (short) knowledge transfer session for the team on how that works

**Comment by LeelaChacha** [comment]
@ruanxin the knowledge transfer session (in AC) already took place right?
In the CRD Upgrade meeting, you went over the Hubs and Spokes pattern and showed the code as well. Is this AC still required?

**Comment by LeelaChacha** [comment]
The SetVersionPriority function is apparently important for the the lifecycle manager to work. Tests are failing if it is removed. I cannot find what it exactly does. But I'll leave it in.
