### ISSUE TITLE
Support remote installation of modules in private registries

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#654]
**Description**

Right now the Lifecycle Manager in the Control Plane provides full support for manifests that are located in repositories secured with credentials: https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/config-private-registry.md

This however, does not work when the ModuleTemplate is located in the runtime cluster (referenced by the `remoteModuleTemplateRef` in Kyma CR). Creating such a secret in the runtime cluster should be possible, as for now - Lifecycle Manager does the lookup only in the Control Plane cluster:
```
error creating repository from spec: no auth secret found
```

**Reasons**

We want to provide the possibility to install modules from private registries in remote mode.

**Acceptance Criteria**

- [x] It is possible to install a remote module that is in the private OCI registry.
- [x] KLM should fetch credentials secret from same cluster as module template is installed (i.e. SKR).
- [x] Improve documentation ([dev tutorial](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/config-private-registry.md),  etc.).
- [x] Add section regarding remote module template in [Kyma CR doc](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md)
- [x] For Testing: Use [existing test](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/manifest/v1beta1/keychain_test.go) as inspiration.
    - [x] If modules template contains auth label, KLM should error out if no secret in SKR.

**Comment by anirudhprasad-sap** [comment]
@lindnerby @nesmabadr - I see that PR with the fix was merged and the build was successful. But in my cluster, I am still getting the same error.

![image](https://github.com/kyma-project/lifecycle-manager/assets/126493692/ebc011a6-5193-4c43-a814-0d3ab07ae0f3)

Can you please let me know when will this fix be available in my cluster?

FYI: My cluster API Server Address - https://api.d2bba1f.stage.kyma.ondemand.com

**Comment by anirudhprasad-sap** [comment]
Update- It started working today. Not sure if there was any update on the stage environment today.

![image](https://github.com/kyma-project/lifecycle-manager/assets/126493692/a1fe610c-c4ca-493b-b036-83ee54a39870)

Thanks for the help.

**Comment by janmedrek** [comment]
@anirudhprasad-sap confirmed with me that the solution works now. 🙂
