### ISSUE TITLE
Migrate jellyfish pipelines from `gcloud` VM

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/lifecycle-manager#682]
**Description**

The `gcloud` VM that we use in some pipelines is going to be deprecated. 
We should refactor the pipelines in question to use the new `k3d-dind-e2e` provided by our DevOps team, as indicated [here](https://github.com/kyma-project/test-infra/issues/7862).

Affected pipeline:
[unstable-cli](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/unstable-cli)

**ACs**

- Identify pipelines that use `gcloud` VMs
- Use the `k3d-dind-e2e` instead

**Comment by lindnerby** [comment]
VMs are created within these scripts:
1. prow/scripts/reconciler-publish-unstable-cli.sh
2. prow/scripts/provision-vm-and-start-kyma-k3d.sh
3. prow/scripts/provision-vm-and-start-reconciler-k3d.sh
4. prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
5. prow/scripts/provision-vm-and-start-kyma-upgrade-k3d.sh

Pipelines affect owned by Jellyfish using one of these scripts (including ref):
- [ ] unstable-cli (1)
- [ ] pre-main-reconciler-integration-k3d (3)
- [ ] pre-main-reconcile-cli-integration-kyma-latest-k3d (4)
- [ ] pre-main-reconciler-cli-integration-kyma-main-k3d (4)
- [ ] pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d (4)
- [ ] pre-dev-reconciler-integration-k3d (3)
- [ ] kyma-upgrade-k3d-kyma2-to-main (5)

**Comment by halamix2** [comment]
Linking back to https://github.com/kyma-project/test-infra/issues/7862

**Comment by lindnerby** [comment]
https://github.com/kyma-project/test-infra/pull/8045
