### ISSUE TITLE
Enable forcetypeassert and fix all related linter check

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#694]
type assertion without check will panic program if unexpected error happens, it's a bad practice without this check.

AC
- [x] double-check whether this is handled by the errcheck (see if this is enabled) - [link](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322)
- [x] enable `forcetypeassert` and fix all unchecked type assertion

**Comment by lindnerby** [comment]
Enabled on both LM and CLI.
