### ISSUE TITLE
Have a dedicated schedule process to check and remove non exists kyma metrics

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#700]
**Description**
When Kyma CR is under deleting, LM will try to remove it in `handleDeletingState`, however, this just happens once, if `RemoveKymaStateMetrics` got error, there is no chance to remove the metrics again.

The idea here is, to create a dedicated schedule process to regularly check all existing kymas, and compared with kyma metrics, remove those not existing ones.

**Acceptance Criteria**
- [x] As proposed [here](https://github.com/kyma-project/lifecycle-manager/issues/700#issuecomment-1624345847) switch the statements to have a different order 
- [x] Write e2e test (use deletion e2e test)
    - [x] Create Kyma
    - [x] Check metrics Kyma count
    - [x] Remove Kyma
    - [x] Kyma count in metrics should go down again

# Reopen on 25.10.2023

The quick fix seems not working, we still got report the false positive alert gets triggered. We need to implement the proposal solution, to create a dedicated schedule process to regularly check all existing kymas, and compared with kyma metrics, remove those not existing ones.

**Comment by ruanxin** [comment]
This issue should be refined again, the solution proposed is not necessary, what we need to do is make sure to delete metrics successfully before removing kyma finalizer. https://github.com/kyma-project/lifecycle-manager/blob/main/controllers/kyma_controller.go#L394-L400

**Comment by janmedrek** [comment]
Waiting for the feedback after the https://github.com/kyma-project/lifecycle-manager/pull/993 was merged

**Comment by janmedrek** [comment]
No Kyma CRs are stuck in the `Deleting` state anymore
