### ISSUE TITLE
[Regression Test] For Watcher CR

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#714]
Reference the internal integration test wiki page, add missing integration test for Watcher CR.

AC:

- [x] add missing test case for existing test
- [x] create new test for missing test
- [x] update wiki page accordingly
- [x] Remove `module-manager` from `centralComponents` list for Watcher test

**Comment by LeelaChacha** [comment]
[Wiki updated](https://wiki.one.int.sap/wiki/display/kyma/Lifecycle+Manager+Integration+Test#LifecycleManagerIntegrationTest-WatcherCR)
