### ISSUE TITLE
Basic monitoring for PurgeReconciler in grafana dashboard

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#734]
Now we enabled PurgeReconciler in KCP, however, we don't have any monitoring dashboard configured for this reconcile.

AC
- [x] Expose metrics for Purge reconciler implemented by controler-runtime
- [x] Extend the KLM performance dashboard with the PurgeReconciler metrics (no need for new panels/diagrams)
- [x] All the default metrics visible on the dashboard
- [x] If it is not possible to distinguish the Purge Controller metrics to Kyma Controller metrics -> Implement custom critical metrics (i.e. Process time of purge controller)

**Comment by janmedrek** [comment]
Reopening this one - we need to:
- check implementation for the `purge count` metric (it produces big numbers of purge counts for a small number of clusters)
- introduce improvements to the presentation of the `purge count` metric
