### ISSUE TITLE
Kyma CR is showing incorrect namespace for Telemetry CR

### ISSUE THREAD

**Issue by shorim** [kyma-project/lifecycle-manager#741]
**Description**

The Kyma CR incorrectly shows that the Telemetry CR is in the `kyma-system` namespace:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: Kyma
metadata:
  annotations:
    cli.kyma-project.io/source: deploy
  creationTimestamp: "2023-07-20T21:57:55Z"
  finalizers:
  - operator.kyma-project.io/Kyma
  generation: 2
  labels:
    operator.kyma-project.io/managed-by: lifecycle-manager
    operator.kyma-project.io/sync: "false"
  name: default-kyma
  namespace: kyma-system
  resourceVersion: "154413"
  uid: eb7c13c2-b205-4cb9-8a98-e1f9ac118212
spec:
  channel: regular
  modules:
  - channel: fast
    customResourcePolicy: CreateAndDelete
    name: telemetry
status:
  activeChannel: regular
  conditions:
  - lastTransitionTime: "2023-07-21T12:11:43Z"
    message: all modules are in ready state
    observedGeneration: 2
    reason: Ready
    status: "True"
    type: Modules
  lastOperation:
    lastUpdateTime: "2023-07-21T12:11:43Z"
    operation: kyma is ready
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Ready
    template:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: ModuleTemplate
      metadata:
        generation: 1
        name: moduletemplate-telemetry
        namespace: kcp-system
    version: v0.7.0
  state: Ready
```
However, the Telemetry CRD is actually cluster-scoped: https://github.com/kyma-project/telemetry-manager/blob/main/config/crd/bases/operator.kyma-project.io_telemetries.yaml#L16 and the Telemetry CR is deployed on the cluster level

```
➜ kubectl get telemetry
NAME      GENERATION   AGE   STATE
default   2            14h   Ready
```
It is important to note that this incorrect namespace causes Busola to build a wrong URL for the Telemetry module as shown in this [issue](https://github.com/kyma-project/busola/issues/2512).

**Expected result**

It is expected that the `resource` field for Telemetry in the `modules` list in Kyma CR would look like that:
```
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: ""
```

**Actual result**

Currently, the `resource` field for Telemetry in the `modules` list in Kyma CR incorrectly shows that the Telemetry CR is in the `kyma-system` namespace:
```
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
```

**Steps to reproduce**
It can be reproduced in a single-cluster setup:

1. kyma alpha deploy
2. Download `template.yaml` from the 0.7.0 release: https://github.com/kyma-project/telemetry-manager/releases/tag/0.7.0
3. kubectl apply -f template.yaml
4. kyma alpha enable module telemetry --channel fast

**Troubleshooting**

**Comment by shorim** [comment]
@janmedrek @ruanxin Please check this out

**Comment by jeremyharisch** [comment]
**ACs:**

- Omit`status.modules.resource.namespace` field if resource is cluster scoped
- Since `namespace` is [optional](https://github.com/kyma-project/lifecycle-manager/blob/e28fc6438d8332303db5886137177127387eb2cc/api/v1beta2/kyma_types.go#L212), it should be possible
