### ISSUE TITLE
Relocate purge controller config to management config plane

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#746]
The purge controller related configuration should not put in config/control-plane, they are only specific for KCP environment, if introduced in control-plane profile, will introduce additional process for other non KCP env to handle. For example, Kyma CR can't be deleted because `purge-finalizer` exists.

AC:
- [x] remove purge controller configuration in config/control-plane
- [x] overwrite them in management-config-plane

# Notice

It must make sure config removed in config/control-plane first then introduce into management-config-plane, otherwise it will have duplicate container args exists in final deployment yaml, and will make deployment failed.

**Comment by jeremyharisch** [comment]
https://github.tools.sap/kyma/management-plane-config/pull/3977#issuecomment-3488765
