### ISSUE TITLE
Reference implementation of a CI/CD pipeline with Gherkin support

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#76]
**Description**
Each component in the new reconciler architecture requires CI/CD pipelines. Most  of the components have quite similar requirements for their pipelines. Therefore, a reference pipeline is required which implements the basic CI/CD features (build, validate, test etc.). This reference implementation can be reused by other reconciler components to reduce implementation efforts.

AC:
- [ ] Align with Pandas team to setup Gherkin testing as main test framework
- [ ]  Integrate code checks into CI /CD pipelines (linting etc.)

**Comment by jakobmoellersap** [comment]
Prepared Meeting on Thursday to make sure that we are okay with the functional effort for this testing approach

**Comment by jakobmoellersap** [comment]
Ran meeting, collected feedback, now aligning with central testing efforts

**Comment by jakobmoellersap** [comment]
Central Testing Efforts aligned. Agreed with @ameteiko to prepare a backlog item / story for sampled acceptance testing

**Comment by jakobmoellersap** [comment]
Waiting Alignment from PO @tobiscr and Testing Team (represented by @ameteiko)

**Comment by tobiscr** [comment]
Finally added to Kyma test cases: https://github.com/kyma-project/kyma/pull/15072

**Comment by jakobmoellersap** [comment]
Following Up implementation of Test in https://github.com/kyma-project/kyma/issues/15084

**Comment by tobiscr** [comment]
Second PR: https://github.com/kyma-project/kyma/pull/15103

**Comment by tobiscr** [comment]
Implementation is tracked here: https://github.com/kyma-project/kyma/issues/15084

**Comment by tobiscr** [comment]
Action items:

* Decide which test framework we use (kubetest2, Ginkgo, Gherkin)

**Comment by tobiscr** [comment]
Business cases documented here: https://github.com/kyma-project/kyma/tree/main/tests/components/reconciler/features
