### ISSUE TITLE
Implement Kyma Operator

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#78]
The Kyma operator is responsible to react on changes applied to `Kyma` CR (see #77 ) and triggers required CR updates.

AC:
- [x]  The operator is watching these `Kyma` CRs and, depending on the resource change, creating/updating/deleting related component CRs and reacting to modules by creating manifest CRs
- [x] Kyma status tracking
   - [x] Aggregating conditions based on manifest status to Kyma status
   - [x] Dynamic enqueueing of KYma instances based on failure and processing state
   - [x] Detect and react to component status change for aggregation in Kyma conditions (list of conditions indicating whether Kyma installation is finished)
- [x] Module template handling
    - [x] Watching module templates based on channel, profile and module name
    - [x] Parsing module templates based on OCM component descriptor API
    - [x] Validating and defaulting webhooks to correctly validate OCM descriptor on input
    - [x] Translation of OCM descriptor model into manifest API
- [x] Allow overwrites
    - [x] Allow module based overwrites for channels in Kyma
    - [x] Allow channel based overwrites in Kyma
- [ ] SKR interaction
    - [ ] Accepting listener request for reconciliation of Kyma instance (tracked in https://github.com/kyma-project/runtime-watcher/issues/2)
    - [ ] Verify and fetch `Kubeconfig` for SKR based on secrets (tracked in https://github.com/kyma-project/lifecycle-manager/issues/12)

**Comment by janmedrek** [comment]
The last points are tracked in the separate tickets, closing this one.
