### ISSUE TITLE
Enable Watcher on STAGE

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#813]
**ACs**
- Patch management-controlplane STAGE config to enable Watcher
  - DNS Name && Server hosts: `listener.cp.stage.kyma.cloud.sap`
- Adapt `kyma-requeue-success-interval` Requeue-Intervals (5min)
- blocked by https://github.com/kyma-project/lifecycle-manager/issues/793
- blocked by https://github.com/kyma-project/lifecycle-manager/issues/815
- Create PR to `management-plane-config` && `managment-plane-charts` (branch: chart/lifecycle-manager)

**Comment by jeremyharisch** [comment]
PRs are open, now we need to wait until they have been merged. Stage-Testing will be done afterwards.

**Comment by jeremyharisch** [comment]
Has been verified on Stage: Working 👍
