### ISSUE TITLE
Introduce wrap multi errors using Go standard library

### ISSUE THREAD

**Issue by medmes** [kyma-project/lifecycle-manager#818]
At the moment, We use our own built in [`multierror` package ](https://github.com/kyma-project/lifecycle-manager/blob/e76fb556aa320e9901fc356430b70bb947092363/pkg/types/multi_error.go#L12)in order to handle multi errors. As Go community released the 1.20 version. The wrap multi errors is possible.

**As** a Developer **I want** to use the standard library to handle multi errors by introducing wrapping multiple error.

**Acceptance Criteria:**
- Multi error struct removed from the [KLM](https://github.com/kyma-project/lifecycle-manager/blob/e76fb556aa320e9901fc356430b70bb947092363/pkg/types/multi_error.go#L12) and the [CLI](https://github.com/kyma-project/cli/blob/554b7bcbf94cafa4ff954b8c353ebd51a03a1561/pkg/errs/multierror.go#L11)
- Revisit current multi error handling implementation. 
- Use the standard library to wrap multi error checking (e.g:` func Join(errs ...error) error{//...}`).
- Correct tests accordingly.

**Comment by lindnerby** [comment]
https://github.com/kyma-project/lifecycle-manager/blob/e76fb556aa320e9901fc356430b70bb947092363/pkg/types/multi_error.go#L12
