### ISSUE TITLE
Add Listener metrics to Grafana dashboard

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#830]
/Since the listener metrics are now exposed (https://github.com/kyma-project/lifecycle-manager/issues/750), we need to add them to the Grafana dashboard

**ACs:**
- Add the listener metrics implemented [here](https://github.com/kyma-project/runtime-watcher/blob/main/listener/pkg/metrics/metrics.go) to Grafana dashboard

**Comment by LeelaChacha** [comment]
[Dashboard created](https://grafana.cp.dev.kyma.cloud.sap/d/7T_JCHkSz/kyma-lifecycle-manager-listener)
