### ISSUE TITLE
Too many restarts of skr-webhook

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/lifecycle-manager#858]
Due to the `request-sidecar` container the `skr-webhook` pods on remotes are restarting very frequently, although not needed:
```
Containers:
  server:
    State:          Running
      Started:      Mon, 04 Sep 2023 12:27:28 +0200
    Ready:          True
    Restart Count:  0
  request-sidecar:
    State:          Running
      Started:      Tue, 12 Sep 2023 08:31:15 +0200
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 12 Sep 2023 07:31:14 +0200
      Finished:     Tue, 12 Sep 2023 08:31:14 +0200
    Ready:          True
    Restart Count:  188
```
We need to investigate, it's roundabout restarting every hour and the sidecar has initial sleep of 60m.

ACs;
- [x] Double-check if side-car is necessary, remove if not needed
- [x] skr-webhook should not restart that often

**Comment by ruanxin** [comment]
```
│ NAME↑            PF IMAGE                                                                           READY STATE    INIT   RESTARTS PROBES(L:R) CPU MEM CPU/R:L MEM/R:L %CPU/R %CPU/L MEM/R │
│ request-sidecar  ●  europe-docker.pkg.dev/kyma-project/prod/external/alpine:3.17.4                  true  Running  false        24 off:off       0   0  10:100  20:200      0      0     1 │
│ server           ●  europe-docker.pkg.dev/kyma-project/prod/runtime-watcher-skr:v20230824-f4459bad  true  Running  false         0 off:off       1  18  10:100  20:200     10      1    92 │
│                                                                                                                                                                                            │
│                                                                                                                                                                                            │

```
the restart happens only in `request-sidecar` container

**Comment by lindnerby** [comment]
> ```
> │ NAME↑            PF IMAGE                                                                           READY STATE    INIT   RESTARTS PROBES(L:R) CPU MEM CPU/R:L MEM/R:L %CPU/R %CPU/L MEM/R │
> │ request-sidecar  ●  europe-docker.pkg.dev/kyma-project/prod/external/alpine:3.17.4                  true  Running  false        24 off:off       0   0  10:100  20:200      0      0     1 │
> │ server           ●  europe-docker.pkg.dev/kyma-project/prod/runtime-watcher-skr:v20230824-f4459bad  true  Running  false         0 off:off       1  18  10:100  20:200     10      1    92 │
> │                                                                                                                                                                                            │
> │                                                                                                                                                                                            │
> ```
> 
> the restart happens only in `request-sidecar` container

Yes as written in the description. We should have a look if we can remove it
