### ISSUE TITLE
upgrade controller-runtime to latest version

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#880]
https://github.com/kyma-project/lifecycle-manager/pull/874 Bumps [sigs.k8s.io/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) from 0.15.1 to 0.16.2. failed because of breaking changes.

AC:
- [ ] fix breaking changes, make sure controller-runtime can be upgraded to latest version

**Comment by janmedrek** [comment]
From the build pipeline:
```
./main.go:131:4: unknown field MetricsBindAddress in struct literal of type "sigs.k8s.io/controller-runtime/pkg/manager".Options
./main.go:132:4: unknown field Port in struct literal of type "sigs.k8s.io/controller-runtime/pkg/manager".Options
```
