### ISSUE TITLE
get rid of //go:build for smoke test

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#904]
Using go:build tags for smoke tests has provided us with a way to isolate specific files for testing in our codebase. However, this approach has made it challenging to maintain consistent code quality because these files are excluded from other processes, for example, linter detection, shared variables

AC:
- [ ] remove go:build for smoke test
- [ ] exclude smoke test for `make test`
- [ ] fix lint issue

**Comment by jeremyharisch** [comment]
After https://github.com/kyma-project/lifecycle-manager/issues/952 has been implemented , this is not needed any more
