### ISSUE TITLE
Add a test for the skip-reconciliation for the Manifest Controller

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#965]
**Description:**

As a followup to this [issue](https://github.com/kyma-project/lifecycle-manager/issues/937), we need to test the functionality of the skip-reconciliation for the Manifest Controller

**ACs:**
- [x] Add an E2E test for the Manifest Controller [here](https://github.com/kyma-project/lifecycle-manager/blob/main/internal/declarative/v2/test/v1/declarative_test.go) to validate that the reconciliation is skipped if the `operator.kyma-project.io/skip-reconciliation` label exists.

Given kyma CR deployed in KCP Cluster
When enabling Template Operator
Then the Sample CR is deployed on the SKR cluster in Ready state

Given Manifest CR with skip label
When deleting Template Operator deployment
Then the deployment should not been recreated.
When deleting Sample CR
Then the Sample CR should not been recreated.

When removing Manifest CR skip label
Then the deployment should be created.
Then the Sample CR should be created.

**Comment by LeelaChacha** [comment]
> Then the deployment should not been created
do you mean "deleted"? @ruanxin

**Comment by LeelaChacha** [comment]
also @nesmabadr the linked location is the file where the integration tests were located. not the e2e

**Comment by ruanxin** [comment]
> > Then the deployment should not been created
> 
> do you mean "deleted"? @ruanxin

no, what I mean is should not been **recreated**, the deployment should be deleted in previous step "When deleting Template Operator deployment"
