### ISSUE TITLE
make LM api as module

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#992]
LM API is currently used by CLI, and in the future, Kyma CR can be a shared resource for different KCP components. However, directly introduce LM as dependencies to CLI or any other components will bring high coupling and introduce many unnecessary dependencies. e.g: controller-runtime.

If we can refactor LM API as a dedicated go module, and introduce only necessary dependencies for this module, then we can directly use this API for other project with low coupling. 

AC:

- [x] refactor LM API as a dedicated go module, with minimum dependencies
  - get rid of `controller-runtime`
  - keep `ocm`
- [ ] relocated irrelevant code, e.g: webhook to LM `pkg`
- [x] introduce this API as local dependencies for LifecycleManager (use `replace`)
- [x] verify make-targets `build`, `manifest`, `generate`,  `lint`, etc. still work
- [ ] write followup issue to replace LM dependencies in the CLI with the dedicated package
- [ ] communicate the change with the teams depending on the LM (GH discussions + reach out to the teams)

**Comment by nesmabadr** [comment]
Not possible to remove controller-runtime as dependency because it is required for the conversion webhooks, which can not be moved to the `pkg`
